// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_actions.sql

package db

import (
	"context"
)

const getAlertActionByName = `-- name: GetAlertActionByName :one
SELECT id, name, display_name, description, is_state_action, severity_override, created_at, updated_at FROM alert_actions WHERE name = $1
`

func (q *Queries) GetAlertActionByName(ctx context.Context, name string) (AlertAction, error) {
	row := q.db.QueryRow(ctx, getAlertActionByName, name)
	var i AlertAction
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.IsStateAction,
		&i.SeverityOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlertActions = `-- name: ListAlertActions :many
SELECT id, name, display_name, description, is_state_action, severity_override, created_at, updated_at FROM alert_actions ORDER BY display_name ASC
`

func (q *Queries) ListAlertActions(ctx context.Context) ([]AlertAction, error) {
	rows, err := q.db.Query(ctx, listAlertActions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlertAction
	for rows.Next() {
		var i AlertAction
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.IsStateAction,
			&i.SeverityOverride,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
