// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alert_config.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAlertConfigByType = `-- name: GetAlertConfigByType :one
SELECT
    ac.id, ac.alert_type, ac.is_enabled, ac.default_severity, ac.auto_assign_enabled, ac.auto_assign_user_id, ac.auto_assign_rule, ac.auto_assign_conditions, ac.retention_days, ac.auto_resolve_after_days, ac.cleanup_resolved_only, ac.notification_enabled, ac.escalation_enabled, ac.escalation_after_hours, ac.alert_delay_seconds, ac.metadata, ac.created_at, ac.updated_at,
    u.id AS auto_assign_user_id_val,
    u.username AS auto_assign_username,
    u.email AS auto_assign_email,
    u.first_name AS auto_assign_first_name,
    u.last_name AS auto_assign_last_name
FROM alert_config ac
LEFT JOIN users u ON ac.auto_assign_user_id = u.id
WHERE ac.alert_type = $1
`

type GetAlertConfigByTypeRow struct {
	ID                   string           `json:"id"`
	AlertType            string           `json:"alert_type"`
	IsEnabled            bool             `json:"is_enabled"`
	DefaultSeverity      string           `json:"default_severity"`
	AutoAssignEnabled    bool             `json:"auto_assign_enabled"`
	AutoAssignUserID     *string          `json:"auto_assign_user_id"`
	AutoAssignRule       *string          `json:"auto_assign_rule"`
	AutoAssignConditions []byte           `json:"auto_assign_conditions"`
	RetentionDays        *int32           `json:"retention_days"`
	AutoResolveAfterDays *int32           `json:"auto_resolve_after_days"`
	CleanupResolvedOnly  bool             `json:"cleanup_resolved_only"`
	NotificationEnabled  bool             `json:"notification_enabled"`
	EscalationEnabled    bool             `json:"escalation_enabled"`
	EscalationAfterHours *int32           `json:"escalation_after_hours"`
	AlertDelaySeconds    *int32           `json:"alert_delay_seconds"`
	Metadata             []byte           `json:"metadata"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	AutoAssignUserIDVal  *string          `json:"auto_assign_user_id_val"`
	AutoAssignUsername   *string          `json:"auto_assign_username"`
	AutoAssignEmail      *string          `json:"auto_assign_email"`
	AutoAssignFirstName  *string          `json:"auto_assign_first_name"`
	AutoAssignLastName   *string          `json:"auto_assign_last_name"`
}

func (q *Queries) GetAlertConfigByType(ctx context.Context, alertType string) (GetAlertConfigByTypeRow, error) {
	row := q.db.QueryRow(ctx, getAlertConfigByType, alertType)
	var i GetAlertConfigByTypeRow
	err := row.Scan(
		&i.ID,
		&i.AlertType,
		&i.IsEnabled,
		&i.DefaultSeverity,
		&i.AutoAssignEnabled,
		&i.AutoAssignUserID,
		&i.AutoAssignRule,
		&i.AutoAssignConditions,
		&i.RetentionDays,
		&i.AutoResolveAfterDays,
		&i.CleanupResolvedOnly,
		&i.NotificationEnabled,
		&i.EscalationEnabled,
		&i.EscalationAfterHours,
		&i.AlertDelaySeconds,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AutoAssignUserIDVal,
		&i.AutoAssignUsername,
		&i.AutoAssignEmail,
		&i.AutoAssignFirstName,
		&i.AutoAssignLastName,
	)
	return i, err
}

const listAlertConfig = `-- name: ListAlertConfig :many
SELECT
    ac.id, ac.alert_type, ac.is_enabled, ac.default_severity, ac.auto_assign_enabled, ac.auto_assign_user_id, ac.auto_assign_rule, ac.auto_assign_conditions, ac.retention_days, ac.auto_resolve_after_days, ac.cleanup_resolved_only, ac.notification_enabled, ac.escalation_enabled, ac.escalation_after_hours, ac.alert_delay_seconds, ac.metadata, ac.created_at, ac.updated_at,
    u.id AS auto_assign_user_id_val,
    u.username AS auto_assign_username,
    u.email AS auto_assign_email,
    u.first_name AS auto_assign_first_name,
    u.last_name AS auto_assign_last_name
FROM alert_config ac
LEFT JOIN users u ON ac.auto_assign_user_id = u.id
ORDER BY ac.alert_type ASC
`

type ListAlertConfigRow struct {
	ID                   string           `json:"id"`
	AlertType            string           `json:"alert_type"`
	IsEnabled            bool             `json:"is_enabled"`
	DefaultSeverity      string           `json:"default_severity"`
	AutoAssignEnabled    bool             `json:"auto_assign_enabled"`
	AutoAssignUserID     *string          `json:"auto_assign_user_id"`
	AutoAssignRule       *string          `json:"auto_assign_rule"`
	AutoAssignConditions []byte           `json:"auto_assign_conditions"`
	RetentionDays        *int32           `json:"retention_days"`
	AutoResolveAfterDays *int32           `json:"auto_resolve_after_days"`
	CleanupResolvedOnly  bool             `json:"cleanup_resolved_only"`
	NotificationEnabled  bool             `json:"notification_enabled"`
	EscalationEnabled    bool             `json:"escalation_enabled"`
	EscalationAfterHours *int32           `json:"escalation_after_hours"`
	AlertDelaySeconds    *int32           `json:"alert_delay_seconds"`
	Metadata             []byte           `json:"metadata"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	AutoAssignUserIDVal  *string          `json:"auto_assign_user_id_val"`
	AutoAssignUsername   *string          `json:"auto_assign_username"`
	AutoAssignEmail      *string          `json:"auto_assign_email"`
	AutoAssignFirstName  *string          `json:"auto_assign_first_name"`
	AutoAssignLastName   *string          `json:"auto_assign_last_name"`
}

func (q *Queries) ListAlertConfig(ctx context.Context) ([]ListAlertConfigRow, error) {
	rows, err := q.db.Query(ctx, listAlertConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertConfigRow
	for rows.Next() {
		var i ListAlertConfigRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertType,
			&i.IsEnabled,
			&i.DefaultSeverity,
			&i.AutoAssignEnabled,
			&i.AutoAssignUserID,
			&i.AutoAssignRule,
			&i.AutoAssignConditions,
			&i.RetentionDays,
			&i.AutoResolveAfterDays,
			&i.CleanupResolvedOnly,
			&i.NotificationEnabled,
			&i.EscalationEnabled,
			&i.EscalationAfterHours,
			&i.AlertDelaySeconds,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AutoAssignUserIDVal,
			&i.AutoAssignUsername,
			&i.AutoAssignEmail,
			&i.AutoAssignFirstName,
			&i.AutoAssignLastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlertConfig = `-- name: UpsertAlertConfig :one
INSERT INTO alert_config (
    id, alert_type, is_enabled, default_severity,
    auto_assign_enabled, auto_assign_user_id, auto_assign_rule, auto_assign_conditions,
    retention_days, auto_resolve_after_days, cleanup_resolved_only,
    notification_enabled, escalation_enabled, escalation_after_hours, alert_delay_seconds, metadata,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, COALESCE($16, '{}'::jsonb),
    NOW(), NOW()
)
ON CONFLICT (alert_type) DO UPDATE SET
    is_enabled = EXCLUDED.is_enabled,
    default_severity = EXCLUDED.default_severity,
    auto_assign_enabled = EXCLUDED.auto_assign_enabled,
    auto_assign_user_id = EXCLUDED.auto_assign_user_id,
    auto_assign_rule = EXCLUDED.auto_assign_rule,
    auto_assign_conditions = EXCLUDED.auto_assign_conditions,
    retention_days = EXCLUDED.retention_days,
    auto_resolve_after_days = EXCLUDED.auto_resolve_after_days,
    cleanup_resolved_only = EXCLUDED.cleanup_resolved_only,
    notification_enabled = EXCLUDED.notification_enabled,
    escalation_enabled = EXCLUDED.escalation_enabled,
    escalation_after_hours = EXCLUDED.escalation_after_hours,
    alert_delay_seconds = EXCLUDED.alert_delay_seconds,
    metadata = EXCLUDED.metadata,
    updated_at = NOW()
RETURNING id, alert_type, is_enabled, default_severity, auto_assign_enabled, auto_assign_user_id, auto_assign_rule, auto_assign_conditions, retention_days, auto_resolve_after_days, cleanup_resolved_only, notification_enabled, escalation_enabled, escalation_after_hours, alert_delay_seconds, metadata, created_at, updated_at
`

type UpsertAlertConfigParams struct {
	ID                   string      `json:"id"`
	AlertType            string      `json:"alert_type"`
	IsEnabled            bool        `json:"is_enabled"`
	DefaultSeverity      string      `json:"default_severity"`
	AutoAssignEnabled    bool        `json:"auto_assign_enabled"`
	AutoAssignUserID     *string     `json:"auto_assign_user_id"`
	AutoAssignRule       *string     `json:"auto_assign_rule"`
	AutoAssignConditions []byte      `json:"auto_assign_conditions"`
	RetentionDays        *int32      `json:"retention_days"`
	AutoResolveAfterDays *int32      `json:"auto_resolve_after_days"`
	CleanupResolvedOnly  bool        `json:"cleanup_resolved_only"`
	NotificationEnabled  bool        `json:"notification_enabled"`
	EscalationEnabled    bool        `json:"escalation_enabled"`
	EscalationAfterHours *int32      `json:"escalation_after_hours"`
	AlertDelaySeconds    *int32      `json:"alert_delay_seconds"`
	Column16             interface{} `json:"column_16"`
}

func (q *Queries) UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error) {
	row := q.db.QueryRow(ctx, upsertAlertConfig,
		arg.ID,
		arg.AlertType,
		arg.IsEnabled,
		arg.DefaultSeverity,
		arg.AutoAssignEnabled,
		arg.AutoAssignUserID,
		arg.AutoAssignRule,
		arg.AutoAssignConditions,
		arg.RetentionDays,
		arg.AutoResolveAfterDays,
		arg.CleanupResolvedOnly,
		arg.NotificationEnabled,
		arg.EscalationEnabled,
		arg.EscalationAfterHours,
		arg.AlertDelaySeconds,
		arg.Column16,
	)
	var i AlertConfig
	err := row.Scan(
		&i.ID,
		&i.AlertType,
		&i.IsEnabled,
		&i.DefaultSeverity,
		&i.AutoAssignEnabled,
		&i.AutoAssignUserID,
		&i.AutoAssignRule,
		&i.AutoAssignConditions,
		&i.RetentionDays,
		&i.AutoResolveAfterDays,
		&i.CleanupResolvedOnly,
		&i.NotificationEnabled,
		&i.EscalationEnabled,
		&i.EscalationAfterHours,
		&i.AlertDelaySeconds,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
