// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auto_enrollment_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAutoEnrollmentToken = `-- name: CreateAutoEnrollmentToken :exec
INSERT INTO auto_enrollment_tokens (
    id, token_name, token_key, token_secret,
    created_by_user_id, is_active, allowed_ip_ranges,
    max_hosts_per_day, default_host_group_id,
    expires_at, metadata, scopes, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type CreateAutoEnrollmentTokenParams struct {
	ID                 string           `json:"id"`
	TokenName          string           `json:"token_name"`
	TokenKey           string           `json:"token_key"`
	TokenSecret        string           `json:"token_secret"`
	CreatedByUserID    *string          `json:"created_by_user_id"`
	IsActive           bool             `json:"is_active"`
	AllowedIpRanges    []string         `json:"allowed_ip_ranges"`
	MaxHostsPerDay     int32            `json:"max_hosts_per_day"`
	DefaultHostGroupID *string          `json:"default_host_group_id"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	Metadata           []byte           `json:"metadata"`
	Scopes             []byte           `json:"scopes"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateAutoEnrollmentToken(ctx context.Context, arg CreateAutoEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, createAutoEnrollmentToken,
		arg.ID,
		arg.TokenName,
		arg.TokenKey,
		arg.TokenSecret,
		arg.CreatedByUserID,
		arg.IsActive,
		arg.AllowedIpRanges,
		arg.MaxHostsPerDay,
		arg.DefaultHostGroupID,
		arg.ExpiresAt,
		arg.Metadata,
		arg.Scopes,
		arg.UpdatedAt,
	)
	return err
}

const deleteAutoEnrollmentToken = `-- name: DeleteAutoEnrollmentToken :exec
DELETE FROM auto_enrollment_tokens WHERE id = $1
`

func (q *Queries) DeleteAutoEnrollmentToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAutoEnrollmentToken, id)
	return err
}

const getAutoEnrollmentTokenByID = `-- name: GetAutoEnrollmentTokenByID :one
SELECT
    t.id, t.token_name, t.token_key, t.is_active,
    t.allowed_ip_ranges, t.max_hosts_per_day, t.hosts_created_today,
    t.last_used_at, t.expires_at, t.created_at, t.updated_at,
    t.default_host_group_id, t.metadata, t.scopes, t.created_by_user_id,
    hg.id   AS hg_id,   hg.name AS hg_name,   hg.color AS hg_color,
    u.id    AS u_id,     u.username AS u_username,
    u.first_name AS u_first_name, u.last_name AS u_last_name
FROM auto_enrollment_tokens t
LEFT JOIN host_groups hg ON hg.id = t.default_host_group_id
LEFT JOIN users u ON u.id = t.created_by_user_id
WHERE t.id = $1
`

type GetAutoEnrollmentTokenByIDRow struct {
	ID                 string           `json:"id"`
	TokenName          string           `json:"token_name"`
	TokenKey           string           `json:"token_key"`
	IsActive           bool             `json:"is_active"`
	AllowedIpRanges    []string         `json:"allowed_ip_ranges"`
	MaxHostsPerDay     int32            `json:"max_hosts_per_day"`
	HostsCreatedToday  int32            `json:"hosts_created_today"`
	LastUsedAt         pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	DefaultHostGroupID *string          `json:"default_host_group_id"`
	Metadata           []byte           `json:"metadata"`
	Scopes             []byte           `json:"scopes"`
	CreatedByUserID    *string          `json:"created_by_user_id"`
	HgID               *string          `json:"hg_id"`
	HgName             *string          `json:"hg_name"`
	HgColor            *string          `json:"hg_color"`
	UID                *string          `json:"u_id"`
	UUsername          *string          `json:"u_username"`
	UFirstName         *string          `json:"u_first_name"`
	ULastName          *string          `json:"u_last_name"`
}

func (q *Queries) GetAutoEnrollmentTokenByID(ctx context.Context, id string) (GetAutoEnrollmentTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, getAutoEnrollmentTokenByID, id)
	var i GetAutoEnrollmentTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.TokenName,
		&i.TokenKey,
		&i.IsActive,
		&i.AllowedIpRanges,
		&i.MaxHostsPerDay,
		&i.HostsCreatedToday,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DefaultHostGroupID,
		&i.Metadata,
		&i.Scopes,
		&i.CreatedByUserID,
		&i.HgID,
		&i.HgName,
		&i.HgColor,
		&i.UID,
		&i.UUsername,
		&i.UFirstName,
		&i.ULastName,
	)
	return i, err
}

const getAutoEnrollmentTokenByKey = `-- name: GetAutoEnrollmentTokenByKey :one
SELECT id, token_name, token_key, token_secret, created_by_user_id, is_active, allowed_ip_ranges, max_hosts_per_day, hosts_created_today, last_reset_date, default_host_group_id, created_at, updated_at, last_used_at, expires_at, metadata, scopes FROM auto_enrollment_tokens WHERE token_key = $1
`

func (q *Queries) GetAutoEnrollmentTokenByKey(ctx context.Context, tokenKey string) (AutoEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getAutoEnrollmentTokenByKey, tokenKey)
	var i AutoEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenName,
		&i.TokenKey,
		&i.TokenSecret,
		&i.CreatedByUserID,
		&i.IsActive,
		&i.AllowedIpRanges,
		&i.MaxHostsPerDay,
		&i.HostsCreatedToday,
		&i.LastResetDate,
		&i.DefaultHostGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.Scopes,
	)
	return i, err
}

const getAutoEnrollmentTokenRaw = `-- name: GetAutoEnrollmentTokenRaw :one
SELECT id, token_name, token_key, token_secret, created_by_user_id, is_active, allowed_ip_ranges, max_hosts_per_day, hosts_created_today, last_reset_date, default_host_group_id, created_at, updated_at, last_used_at, expires_at, metadata, scopes FROM auto_enrollment_tokens WHERE id = $1
`

func (q *Queries) GetAutoEnrollmentTokenRaw(ctx context.Context, id string) (AutoEnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getAutoEnrollmentTokenRaw, id)
	var i AutoEnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.TokenName,
		&i.TokenKey,
		&i.TokenSecret,
		&i.CreatedByUserID,
		&i.IsActive,
		&i.AllowedIpRanges,
		&i.MaxHostsPerDay,
		&i.HostsCreatedToday,
		&i.LastResetDate,
		&i.DefaultHostGroupID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.Metadata,
		&i.Scopes,
	)
	return i, err
}

const incrementAutoEnrollmentHostsCreated = `-- name: IncrementAutoEnrollmentHostsCreated :exec
UPDATE auto_enrollment_tokens SET
    hosts_created_today = CASE WHEN last_reset_date::date < CURRENT_DATE THEN 1 ELSE hosts_created_today + 1 END,
    last_reset_date = CASE WHEN last_reset_date::date < CURRENT_DATE THEN CURRENT_DATE ELSE last_reset_date END,
    last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) IncrementAutoEnrollmentHostsCreated(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementAutoEnrollmentHostsCreated, id)
	return err
}

const listAutoEnrollmentTokens = `-- name: ListAutoEnrollmentTokens :many
SELECT
    t.id, t.token_name, t.token_key, t.is_active,
    t.allowed_ip_ranges, t.max_hosts_per_day, t.hosts_created_today,
    t.last_used_at, t.expires_at, t.created_at, t.default_host_group_id,
    t.metadata, t.scopes,
    hg.id   AS hg_id,   hg.name AS hg_name,   hg.color AS hg_color,
    u.id    AS u_id,     u.username AS u_username,
    u.first_name AS u_first_name, u.last_name AS u_last_name
FROM auto_enrollment_tokens t
LEFT JOIN host_groups hg ON hg.id = t.default_host_group_id
LEFT JOIN users u ON u.id = t.created_by_user_id
ORDER BY t.created_at DESC
`

type ListAutoEnrollmentTokensRow struct {
	ID                 string           `json:"id"`
	TokenName          string           `json:"token_name"`
	TokenKey           string           `json:"token_key"`
	IsActive           bool             `json:"is_active"`
	AllowedIpRanges    []string         `json:"allowed_ip_ranges"`
	MaxHostsPerDay     int32            `json:"max_hosts_per_day"`
	HostsCreatedToday  int32            `json:"hosts_created_today"`
	LastUsedAt         pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	CreatedAt          pgtype.Timestamp `json:"created_at"`
	DefaultHostGroupID *string          `json:"default_host_group_id"`
	Metadata           []byte           `json:"metadata"`
	Scopes             []byte           `json:"scopes"`
	HgID               *string          `json:"hg_id"`
	HgName             *string          `json:"hg_name"`
	HgColor            *string          `json:"hg_color"`
	UID                *string          `json:"u_id"`
	UUsername          *string          `json:"u_username"`
	UFirstName         *string          `json:"u_first_name"`
	ULastName          *string          `json:"u_last_name"`
}

func (q *Queries) ListAutoEnrollmentTokens(ctx context.Context) ([]ListAutoEnrollmentTokensRow, error) {
	rows, err := q.db.Query(ctx, listAutoEnrollmentTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAutoEnrollmentTokensRow
	for rows.Next() {
		var i ListAutoEnrollmentTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenName,
			&i.TokenKey,
			&i.IsActive,
			&i.AllowedIpRanges,
			&i.MaxHostsPerDay,
			&i.HostsCreatedToday,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.DefaultHostGroupID,
			&i.Metadata,
			&i.Scopes,
			&i.HgID,
			&i.HgName,
			&i.HgColor,
			&i.UID,
			&i.UUsername,
			&i.UFirstName,
			&i.ULastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAutoEnrollmentToken = `-- name: UpdateAutoEnrollmentToken :exec
UPDATE auto_enrollment_tokens SET
    token_name = $1,
    is_active = $2,
    max_hosts_per_day = $3,
    allowed_ip_ranges = $4,
    expires_at = $5,
    default_host_group_id = $6,
    scopes = $7,
    updated_at = $8
WHERE id = $9
`

type UpdateAutoEnrollmentTokenParams struct {
	TokenName          string           `json:"token_name"`
	IsActive           bool             `json:"is_active"`
	MaxHostsPerDay     int32            `json:"max_hosts_per_day"`
	AllowedIpRanges    []string         `json:"allowed_ip_ranges"`
	ExpiresAt          pgtype.Timestamp `json:"expires_at"`
	DefaultHostGroupID *string          `json:"default_host_group_id"`
	Scopes             []byte           `json:"scopes"`
	UpdatedAt          pgtype.Timestamp `json:"updated_at"`
	ID                 string           `json:"id"`
}

func (q *Queries) UpdateAutoEnrollmentToken(ctx context.Context, arg UpdateAutoEnrollmentTokenParams) error {
	_, err := q.db.Exec(ctx, updateAutoEnrollmentToken,
		arg.TokenName,
		arg.IsActive,
		arg.MaxHostsPerDay,
		arg.AllowedIpRanges,
		arg.ExpiresAt,
		arg.DefaultHostGroupID,
		arg.Scopes,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAutoEnrollmentTokenLastUsedAt = `-- name: UpdateAutoEnrollmentTokenLastUsedAt :exec
UPDATE auto_enrollment_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateAutoEnrollmentTokenLastUsedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAutoEnrollmentTokenLastUsedAt, id)
	return err
}
