// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: compliance_rules.sql

package db

import (
	"context"
)

const createComplianceRule = `-- name: CreateComplianceRule :one
INSERT INTO compliance_rules (id, profile_id, rule_ref, title, description, rationale, severity, section, remediation)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, profile_id, rule_ref, title, description, rationale, severity, section, remediation
`

type CreateComplianceRuleParams struct {
	ID          string  `json:"id"`
	ProfileID   string  `json:"profile_id"`
	RuleRef     string  `json:"rule_ref"`
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Rationale   *string `json:"rationale"`
	Severity    *string `json:"severity"`
	Section     *string `json:"section"`
	Remediation *string `json:"remediation"`
}

func (q *Queries) CreateComplianceRule(ctx context.Context, arg CreateComplianceRuleParams) (ComplianceRule, error) {
	row := q.db.QueryRow(ctx, createComplianceRule,
		arg.ID,
		arg.ProfileID,
		arg.RuleRef,
		arg.Title,
		arg.Description,
		arg.Rationale,
		arg.Severity,
		arg.Section,
		arg.Remediation,
	)
	var i ComplianceRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RuleRef,
		&i.Title,
		&i.Description,
		&i.Rationale,
		&i.Severity,
		&i.Section,
		&i.Remediation,
	)
	return i, err
}

const getComplianceRuleByID = `-- name: GetComplianceRuleByID :one
SELECT cr.id, cr.profile_id, cr.rule_ref, cr.title, cr.description, cr.rationale, cr.severity, cr.section, cr.remediation,
       cp.id as profile_id_val, cp.type as profile_type, cp.name as profile_name
FROM compliance_rules cr
JOIN compliance_profiles cp ON cp.id = cr.profile_id
WHERE cr.id = $1
`

type GetComplianceRuleByIDRow struct {
	ID           string  `json:"id"`
	ProfileID    string  `json:"profile_id"`
	RuleRef      string  `json:"rule_ref"`
	Title        string  `json:"title"`
	Description  *string `json:"description"`
	Rationale    *string `json:"rationale"`
	Severity     *string `json:"severity"`
	Section      *string `json:"section"`
	Remediation  *string `json:"remediation"`
	ProfileIDVal string  `json:"profile_id_val"`
	ProfileType  string  `json:"profile_type"`
	ProfileName  string  `json:"profile_name"`
}

func (q *Queries) GetComplianceRuleByID(ctx context.Context, id string) (GetComplianceRuleByIDRow, error) {
	row := q.db.QueryRow(ctx, getComplianceRuleByID, id)
	var i GetComplianceRuleByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RuleRef,
		&i.Title,
		&i.Description,
		&i.Rationale,
		&i.Severity,
		&i.Section,
		&i.Remediation,
		&i.ProfileIDVal,
		&i.ProfileType,
		&i.ProfileName,
	)
	return i, err
}

const getComplianceRuleByProfileAndRef = `-- name: GetComplianceRuleByProfileAndRef :one
SELECT id, profile_id, rule_ref, title, description, rationale, severity, section, remediation
FROM compliance_rules
WHERE profile_id = $1 AND rule_ref = $2
`

type GetComplianceRuleByProfileAndRefParams struct {
	ProfileID string `json:"profile_id"`
	RuleRef   string `json:"rule_ref"`
}

func (q *Queries) GetComplianceRuleByProfileAndRef(ctx context.Context, arg GetComplianceRuleByProfileAndRefParams) (ComplianceRule, error) {
	row := q.db.QueryRow(ctx, getComplianceRuleByProfileAndRef, arg.ProfileID, arg.RuleRef)
	var i ComplianceRule
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.RuleRef,
		&i.Title,
		&i.Description,
		&i.Rationale,
		&i.Severity,
		&i.Section,
		&i.Remediation,
	)
	return i, err
}

const listComplianceRulesByProfile = `-- name: ListComplianceRulesByProfile :many
SELECT id, profile_id, rule_ref, title, description, rationale, severity, section, remediation
FROM compliance_rules
WHERE profile_id = $1
`

func (q *Queries) ListComplianceRulesByProfile(ctx context.Context, profileID string) ([]ComplianceRule, error) {
	rows, err := q.db.Query(ctx, listComplianceRulesByProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ComplianceRule
	for rows.Next() {
		var i ComplianceRule
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.RuleRef,
			&i.Title,
			&i.Description,
			&i.Rationale,
			&i.Severity,
			&i.Section,
			&i.Remediation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComplianceRule = `-- name: UpdateComplianceRule :exec
UPDATE compliance_rules
SET title = COALESCE($1::text, title),
    description = COALESCE($2::text, description),
    severity = COALESCE($3::text, severity),
    section = COALESCE($4::text, section),
    remediation = COALESCE($5::text, remediation)
WHERE id = $6
`

type UpdateComplianceRuleParams struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Severity    *string `json:"severity"`
	Section     *string `json:"section"`
	Remediation *string `json:"remediation"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateComplianceRule(ctx context.Context, arg UpdateComplianceRuleParams) error {
	_, err := q.db.Exec(ctx, updateComplianceRule,
		arg.Title,
		arg.Description,
		arg.Severity,
		arg.Section,
		arg.Remediation,
		arg.ID,
	)
	return err
}
