// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: docker.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countContainers = `-- name: CountContainers :one
SELECT COUNT(*)::int FROM docker_containers
WHERE ($1::text IS NULL OR status = $1)
AND ($2::text IS NULL OR host_id = $2)
AND ($3::text IS NULL OR image_id = $3)
AND ($4::text IS NULL OR name ILIKE '%' || $4 || '%' OR image_name ILIKE '%' || $4 || '%')
`

type CountContainersParams struct {
	Status  *string `json:"status"`
	HostID  *string `json:"host_id"`
	ImageID *string `json:"image_id"`
	Search  *string `json:"search"`
}

func (q *Queries) CountContainers(ctx context.Context, arg CountContainersParams) (int32, error) {
	row := q.db.QueryRow(ctx, countContainers,
		arg.Status,
		arg.HostID,
		arg.ImageID,
		arg.Search,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countContainersByImageID = `-- name: CountContainersByImageID :one
SELECT COUNT(*)::int FROM docker_containers WHERE image_id = $1
`

func (q *Queries) CountContainersByImageID(ctx context.Context, imageID *string) (int32, error) {
	row := q.db.QueryRow(ctx, countContainersByImageID, imageID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countDockerHosts = `-- name: CountDockerHosts :one
SELECT COUNT(DISTINCT host_id)::int FROM docker_containers
`

// Dashboard stats
func (q *Queries) CountDockerHosts(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countDockerHosts)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countImages = `-- name: CountImages :one
SELECT COUNT(*)::int FROM docker_images
WHERE ($1::text IS NULL OR source = $1)
AND ($2::text IS NULL OR repository ILIKE '%' || $2 || '%' OR tag ILIKE '%' || $2 || '%')
`

type CountImagesParams struct {
	Source *string `json:"source"`
	Search *string `json:"search"`
}

func (q *Queries) CountImages(ctx context.Context, arg CountImagesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countImages, arg.Source, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countNetworks = `-- name: CountNetworks :one
SELECT COUNT(*)::int FROM docker_networks
WHERE ($1::text IS NULL OR driver = $1)
AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
`

type CountNetworksParams struct {
	Driver *string `json:"driver"`
	Search *string `json:"search"`
}

func (q *Queries) CountNetworks(ctx context.Context, arg CountNetworksParams) (int32, error) {
	row := q.db.QueryRow(ctx, countNetworks, arg.Driver, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countNetworksByHostID = `-- name: CountNetworksByHostID :one
SELECT COUNT(*)::int FROM docker_networks WHERE host_id = $1
`

func (q *Queries) CountNetworksByHostID(ctx context.Context, hostID string) (int32, error) {
	row := q.db.QueryRow(ctx, countNetworksByHostID, hostID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVolumes = `-- name: CountVolumes :one
SELECT COUNT(*)::int FROM docker_volumes
WHERE ($1::text IS NULL OR driver = $1)
AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
`

type CountVolumesParams struct {
	Driver *string `json:"driver"`
	Search *string `json:"search"`
}

func (q *Queries) CountVolumes(ctx context.Context, arg CountVolumesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countVolumes, arg.Driver, arg.Search)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVolumesByHostID = `-- name: CountVolumesByHostID :one
SELECT COUNT(*)::int FROM docker_volumes WHERE host_id = $1
`

func (q *Queries) CountVolumesByHostID(ctx context.Context, hostID string) (int32, error) {
	row := q.db.QueryRow(ctx, countVolumesByHostID, hostID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteContainer = `-- name: DeleteContainer :exec
DELETE FROM docker_containers WHERE id = $1
`

func (q *Queries) DeleteContainer(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteContainer, id)
	return err
}

const deleteContainersByIDs = `-- name: DeleteContainersByIDs :exec
DELETE FROM docker_containers WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteContainersByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteContainersByIDs, dollar_1)
	return err
}

const deleteImageByID = `-- name: DeleteImageByID :exec
DELETE FROM docker_images WHERE id = $1
`

func (q *Queries) DeleteImageByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteImageByID, id)
	return err
}

const deleteImageUpdatesByImageID = `-- name: DeleteImageUpdatesByImageID :exec
DELETE FROM docker_image_updates WHERE image_id = $1
`

func (q *Queries) DeleteImageUpdatesByImageID(ctx context.Context, imageID string) error {
	_, err := q.db.Exec(ctx, deleteImageUpdatesByImageID, imageID)
	return err
}

const deleteImagesByIDs = `-- name: DeleteImagesByIDs :exec
DELETE FROM docker_images WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteImagesByIDs(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteImagesByIDs, dollar_1)
	return err
}

const deleteNetwork = `-- name: DeleteNetwork :exec
DELETE FROM docker_networks WHERE id = $1
`

func (q *Queries) DeleteNetwork(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteNetwork, id)
	return err
}

const deleteVolume = `-- name: DeleteVolume :exec
DELETE FROM docker_volumes WHERE id = $1
`

func (q *Queries) DeleteVolume(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVolume, id)
	return err
}

const getContainerByID = `-- name: GetContainerByID :one
SELECT id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked FROM docker_containers WHERE id = $1
`

// Containers
func (q *Queries) GetContainerByID(ctx context.Context, id string) (DockerContainer, error) {
	row := q.db.QueryRow(ctx, getContainerByID, id)
	var i DockerContainer
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.ContainerID,
		&i.Name,
		&i.ImageID,
		&i.ImageName,
		&i.ImageTag,
		&i.Status,
		&i.State,
		&i.Ports,
		&i.Labels,
		&i.CreatedAt,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.LastChecked,
	)
	return i, err
}

const getContainerCountsByImageIDs = `-- name: GetContainerCountsByImageIDs :many
SELECT image_id, COUNT(*)::int as cnt FROM docker_containers WHERE image_id = ANY($1::text[]) GROUP BY image_id
`

type GetContainerCountsByImageIDsRow struct {
	ImageID *string `json:"image_id"`
	Cnt     int32   `json:"cnt"`
}

func (q *Queries) GetContainerCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetContainerCountsByImageIDsRow, error) {
	rows, err := q.db.Query(ctx, getContainerCountsByImageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContainerCountsByImageIDsRow
	for rows.Next() {
		var i GetContainerCountsByImageIDsRow
		if err := rows.Scan(&i.ImageID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainersByHostID = `-- name: GetContainersByHostID :many
SELECT id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked FROM docker_containers WHERE host_id = $1 ORDER BY name ASC
`

func (q *Queries) GetContainersByHostID(ctx context.Context, hostID string) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, getContainersByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerContainer
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ContainerID,
			&i.Name,
			&i.ImageID,
			&i.ImageName,
			&i.ImageTag,
			&i.Status,
			&i.State,
			&i.Ports,
			&i.Labels,
			&i.CreatedAt,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainersByImageID = `-- name: GetContainersByImageID :many
SELECT id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked FROM docker_containers WHERE image_id = $1 AND id != $2 LIMIT 10
`

type GetContainersByImageIDParams struct {
	ImageID *string `json:"image_id"`
	ID      string  `json:"id"`
}

func (q *Queries) GetContainersByImageID(ctx context.Context, arg GetContainersByImageIDParams) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, getContainersByImageID, arg.ImageID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerContainer
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ContainerID,
			&i.Name,
			&i.ImageID,
			&i.ImageName,
			&i.ImageTag,
			&i.Status,
			&i.State,
			&i.Ports,
			&i.Labels,
			&i.CreatedAt,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainersByImageIDAll = `-- name: GetContainersByImageIDAll :many
SELECT id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked FROM docker_containers WHERE image_id = $1 LIMIT 100
`

func (q *Queries) GetContainersByImageIDAll(ctx context.Context, imageID *string) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, getContainersByImageIDAll, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerContainer
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ContainerID,
			&i.Name,
			&i.ImageID,
			&i.ImageName,
			&i.ImageTag,
			&i.Status,
			&i.State,
			&i.Ports,
			&i.Labels,
			&i.CreatedAt,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContainersByStatus = `-- name: GetContainersByStatus :many
SELECT status, COUNT(*)::int as count FROM docker_containers GROUP BY status
`

type GetContainersByStatusRow struct {
	Status string `json:"status"`
	Count  int32  `json:"count"`
}

func (q *Queries) GetContainersByStatus(ctx context.Context) ([]GetContainersByStatusRow, error) {
	rows, err := q.db.Query(ctx, getContainersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetContainersByStatusRow
	for rows.Next() {
		var i GetContainersByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDistinctDockerHostIDs = `-- name: GetDistinctDockerHostIDs :many
SELECT DISTINCT host_id FROM (
    SELECT host_id FROM docker_containers
    UNION
    SELECT host_id FROM docker_volumes
    UNION
    SELECT host_id FROM docker_networks
) AS docker_hosts
`

// Hosts (include hosts with containers, volumes, or networks)
func (q *Queries) GetDistinctDockerHostIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDistinctDockerHostIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var host_id string
		if err := rows.Scan(&host_id); err != nil {
			return nil, err
		}
		items = append(items, host_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDockerDashboardStats = `-- name: GetDockerDashboardStats :one
SELECT
    (SELECT COUNT(*)::int FROM docker_containers),
    (SELECT COUNT(*)::int FROM docker_containers WHERE status = 'running'),
    (SELECT COUNT(*)::int FROM docker_images),
    (SELECT COUNT(*)::int FROM docker_image_updates)
`

type GetDockerDashboardStatsRow struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
	Column4 int32 `json:"column_4"`
}

func (q *Queries) GetDockerDashboardStats(ctx context.Context) (GetDockerDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getDockerDashboardStats)
	var i GetDockerDashboardStatsRow
	err := row.Scan(
		&i.Column1,
		&i.Column2,
		&i.Column3,
		&i.Column4,
	)
	return i, err
}

const getDockerHostsByIDs = `-- name: GetDockerHostsByIDs :many
SELECT id, friendly_name, hostname, ip, os_type, os_version FROM hosts WHERE id = ANY($1::text[])
`

type GetDockerHostsByIDsRow struct {
	ID           string  `json:"id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
	Ip           *string `json:"ip"`
	OsType       string  `json:"os_type"`
	OsVersion    string  `json:"os_version"`
}

func (q *Queries) GetDockerHostsByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getDockerHostsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDockerHostsByIDsRow
	for rows.Next() {
		var i GetDockerHostsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
			&i.OsType,
			&i.OsVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDockerHostsMinimalByIDs = `-- name: GetDockerHostsMinimalByIDs :many
SELECT id, friendly_name, hostname, ip FROM hosts WHERE id = ANY($1::text[])
`

type GetDockerHostsMinimalByIDsRow struct {
	ID           string  `json:"id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
	Ip           *string `json:"ip"`
}

func (q *Queries) GetDockerHostsMinimalByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsMinimalByIDsRow, error) {
	rows, err := q.db.Query(ctx, getDockerHostsMinimalByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDockerHostsMinimalByIDsRow
	for rows.Next() {
		var i GetDockerHostsMinimalByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHostDockerStats = `-- name: GetHostDockerStats :one
SELECT
    COUNT(*)::int,
    COUNT(*) FILTER (WHERE status = 'running')::int,
    COUNT(DISTINCT image_id) FILTER (WHERE image_id IS NOT NULL)::int
FROM docker_containers
WHERE host_id = $1
`

type GetHostDockerStatsRow struct {
	Column1 int32 `json:"column_1"`
	Column2 int32 `json:"column_2"`
	Column3 int32 `json:"column_3"`
}

func (q *Queries) GetHostDockerStats(ctx context.Context, hostID string) (GetHostDockerStatsRow, error) {
	row := q.db.QueryRow(ctx, getHostDockerStats, hostID)
	var i GetHostDockerStatsRow
	err := row.Scan(&i.Column1, &i.Column2, &i.Column3)
	return i, err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, repository, tag, image_id, digest, size_bytes, source, created_at, last_pulled, last_checked, updated_at FROM docker_images WHERE id = $1
`

// Images
func (q *Queries) GetImageByID(ctx context.Context, id string) (DockerImage, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i DockerImage
	err := row.Scan(
		&i.ID,
		&i.Repository,
		&i.Tag,
		&i.ImageID,
		&i.Digest,
		&i.SizeBytes,
		&i.Source,
		&i.CreatedAt,
		&i.LastPulled,
		&i.LastChecked,
		&i.UpdatedAt,
	)
	return i, err
}

const getImageIDByRepositoryTagImageID = `-- name: GetImageIDByRepositoryTagImageID :one
SELECT id FROM docker_images WHERE repository = $1 AND tag = $2 AND image_id = $3
`

type GetImageIDByRepositoryTagImageIDParams struct {
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	ImageID    string `json:"image_id"`
}

func (q *Queries) GetImageIDByRepositoryTagImageID(ctx context.Context, arg GetImageIDByRepositoryTagImageIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getImageIDByRepositoryTagImageID, arg.Repository, arg.Tag, arg.ImageID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getImageUpdatesByImageID = `-- name: GetImageUpdatesByImageID :many
SELECT id, image_id, current_tag, available_tag, is_security_update, severity, changelog_url, created_at, updated_at FROM docker_image_updates WHERE image_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetImageUpdatesByImageID(ctx context.Context, imageID string) ([]DockerImageUpdate, error) {
	rows, err := q.db.Query(ctx, getImageUpdatesByImageID, imageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerImageUpdate
	for rows.Next() {
		var i DockerImageUpdate
		if err := rows.Scan(
			&i.ID,
			&i.ImageID,
			&i.CurrentTag,
			&i.AvailableTag,
			&i.IsSecurityUpdate,
			&i.Severity,
			&i.ChangelogUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesByIDs = `-- name: GetImagesByIDs :many
SELECT id, repository, tag, image_id, digest, size_bytes, source, created_at, last_pulled, last_checked, updated_at FROM docker_images WHERE id = ANY($1::text[])
`

func (q *Queries) GetImagesByIDs(ctx context.Context, dollar_1 []string) ([]DockerImage, error) {
	rows, err := q.db.Query(ctx, getImagesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerImage
	for rows.Next() {
		var i DockerImage
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.Tag,
			&i.ImageID,
			&i.Digest,
			&i.SizeBytes,
			&i.Source,
			&i.CreatedAt,
			&i.LastPulled,
			&i.LastChecked,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImagesBySource = `-- name: GetImagesBySource :many
SELECT source, COUNT(*)::int as count FROM docker_images GROUP BY source
`

type GetImagesBySourceRow struct {
	Source string `json:"source"`
	Count  int32  `json:"count"`
}

func (q *Queries) GetImagesBySource(ctx context.Context) ([]GetImagesBySourceRow, error) {
	rows, err := q.db.Query(ctx, getImagesBySource)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetImagesBySourceRow
	for rows.Next() {
		var i GetImagesBySourceRow
		if err := rows.Scan(&i.Source, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNetworkByID = `-- name: GetNetworkByID :one
SELECT id, host_id, network_id, name, driver, scope, ipv6_enabled, internal, attachable, ingress, config_only, labels, ipam, container_count, created_at, updated_at, last_checked FROM docker_networks WHERE id = $1
`

// Networks
func (q *Queries) GetNetworkByID(ctx context.Context, id string) (DockerNetwork, error) {
	row := q.db.QueryRow(ctx, getNetworkByID, id)
	var i DockerNetwork
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.NetworkID,
		&i.Name,
		&i.Driver,
		&i.Scope,
		&i.Ipv6Enabled,
		&i.Internal,
		&i.Attachable,
		&i.Ingress,
		&i.ConfigOnly,
		&i.Labels,
		&i.Ipam,
		&i.ContainerCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChecked,
	)
	return i, err
}

const getNetworksByHostID = `-- name: GetNetworksByHostID :many
SELECT id, host_id, network_id, name, driver, scope, ipv6_enabled, internal, attachable, ingress, config_only, labels, ipam, container_count, created_at, updated_at, last_checked FROM docker_networks WHERE host_id = $1 ORDER BY name ASC
`

func (q *Queries) GetNetworksByHostID(ctx context.Context, hostID string) ([]DockerNetwork, error) {
	rows, err := q.db.Query(ctx, getNetworksByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerNetwork
	for rows.Next() {
		var i DockerNetwork
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.NetworkID,
			&i.Name,
			&i.Driver,
			&i.Scope,
			&i.Ipv6Enabled,
			&i.Internal,
			&i.Attachable,
			&i.Ingress,
			&i.ConfigOnly,
			&i.Labels,
			&i.Ipam,
			&i.ContainerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateCountsByImageIDs = `-- name: GetUpdateCountsByImageIDs :many
SELECT image_id, COUNT(*)::int as cnt FROM docker_image_updates WHERE image_id = ANY($1::text[]) GROUP BY image_id
`

type GetUpdateCountsByImageIDsRow struct {
	ImageID string `json:"image_id"`
	Cnt     int32  `json:"cnt"`
}

func (q *Queries) GetUpdateCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetUpdateCountsByImageIDsRow, error) {
	rows, err := q.db.Query(ctx, getUpdateCountsByImageIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateCountsByImageIDsRow
	for rows.Next() {
		var i GetUpdateCountsByImageIDsRow
		if err := rows.Scan(&i.ImageID, &i.Cnt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVolumeByID = `-- name: GetVolumeByID :one
SELECT id, host_id, volume_id, name, driver, mountpoint, renderer, scope, labels, options, size_bytes, ref_count, created_at, updated_at, last_checked FROM docker_volumes WHERE id = $1
`

// Volumes
func (q *Queries) GetVolumeByID(ctx context.Context, id string) (DockerVolume, error) {
	row := q.db.QueryRow(ctx, getVolumeByID, id)
	var i DockerVolume
	err := row.Scan(
		&i.ID,
		&i.HostID,
		&i.VolumeID,
		&i.Name,
		&i.Driver,
		&i.Mountpoint,
		&i.Renderer,
		&i.Scope,
		&i.Labels,
		&i.Options,
		&i.SizeBytes,
		&i.RefCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastChecked,
	)
	return i, err
}

const getVolumesByHostID = `-- name: GetVolumesByHostID :many
SELECT id, host_id, volume_id, name, driver, mountpoint, renderer, scope, labels, options, size_bytes, ref_count, created_at, updated_at, last_checked FROM docker_volumes WHERE host_id = $1 ORDER BY name ASC
`

func (q *Queries) GetVolumesByHostID(ctx context.Context, hostID string) ([]DockerVolume, error) {
	rows, err := q.db.Query(ctx, getVolumesByHostID, hostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerVolume
	for rows.Next() {
		var i DockerVolume
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.VolumeID,
			&i.Name,
			&i.Driver,
			&i.Mountpoint,
			&i.Renderer,
			&i.Scope,
			&i.Labels,
			&i.Options,
			&i.SizeBytes,
			&i.RefCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContainers = `-- name: ListContainers :many
SELECT id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked FROM docker_containers
WHERE ($1::text IS NULL OR status = $1)
AND ($2::text IS NULL OR host_id = $2)
AND ($3::text IS NULL OR image_id = $3)
AND ($4::text IS NULL OR name ILIKE '%' || $4 || '%' OR image_name ILIKE '%' || $4 || '%')
ORDER BY updated_at DESC
LIMIT $6 OFFSET $5
`

type ListContainersParams struct {
	Status  *string `json:"status"`
	HostID  *string `json:"host_id"`
	ImageID *string `json:"image_id"`
	Search  *string `json:"search"`
	Offset  int32   `json:"offset"`
	Limit   int32   `json:"limit"`
}

func (q *Queries) ListContainers(ctx context.Context, arg ListContainersParams) ([]DockerContainer, error) {
	rows, err := q.db.Query(ctx, listContainers,
		arg.Status,
		arg.HostID,
		arg.ImageID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerContainer
	for rows.Next() {
		var i DockerContainer
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ContainerID,
			&i.Name,
			&i.ImageID,
			&i.ImageName,
			&i.ImageTag,
			&i.Status,
			&i.State,
			&i.Ports,
			&i.Labels,
			&i.CreatedAt,
			&i.StartedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDockerHostsPaginated = `-- name: ListDockerHostsPaginated :many
SELECT id, friendly_name, hostname, ip FROM hosts
WHERE id IN (
    SELECT DISTINCT host_id FROM docker_containers
    UNION
    SELECT DISTINCT host_id FROM docker_volumes
    UNION
    SELECT DISTINCT host_id FROM docker_networks
)
ORDER BY friendly_name ASC
LIMIT $1 OFFSET $2
`

type ListDockerHostsPaginatedParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDockerHostsPaginatedRow struct {
	ID           string  `json:"id"`
	FriendlyName string  `json:"friendly_name"`
	Hostname     *string `json:"hostname"`
	Ip           *string `json:"ip"`
}

func (q *Queries) ListDockerHostsPaginated(ctx context.Context, arg ListDockerHostsPaginatedParams) ([]ListDockerHostsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listDockerHostsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDockerHostsPaginatedRow
	for rows.Next() {
		var i ListDockerHostsPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FriendlyName,
			&i.Hostname,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImages = `-- name: ListImages :many
SELECT id, repository, tag, image_id, digest, size_bytes, source, created_at, last_pulled, last_checked, updated_at FROM docker_images
WHERE ($1::text IS NULL OR source = $1)
AND ($2::text IS NULL OR repository ILIKE '%' || $2 || '%' OR tag ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC
LIMIT $4 OFFSET $3
`

type ListImagesParams struct {
	Source *string `json:"source"`
	Search *string `json:"search"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListImages(ctx context.Context, arg ListImagesParams) ([]DockerImage, error) {
	rows, err := q.db.Query(ctx, listImages,
		arg.Source,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerImage
	for rows.Next() {
		var i DockerImage
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.Tag,
			&i.ImageID,
			&i.Digest,
			&i.SizeBytes,
			&i.Source,
			&i.CreatedAt,
			&i.LastPulled,
			&i.LastChecked,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworks = `-- name: ListNetworks :many
SELECT id, host_id, network_id, name, driver, scope, ipv6_enabled, internal, attachable, ingress, config_only, labels, ipam, container_count, created_at, updated_at, last_checked FROM docker_networks
WHERE ($1::text IS NULL OR driver = $1)
AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC
LIMIT $4 OFFSET $3
`

type ListNetworksParams struct {
	Driver *string `json:"driver"`
	Search *string `json:"search"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListNetworks(ctx context.Context, arg ListNetworksParams) ([]DockerNetwork, error) {
	rows, err := q.db.Query(ctx, listNetworks,
		arg.Driver,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerNetwork
	for rows.Next() {
		var i DockerNetwork
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.NetworkID,
			&i.Name,
			&i.Driver,
			&i.Scope,
			&i.Ipv6Enabled,
			&i.Internal,
			&i.Attachable,
			&i.Ingress,
			&i.ConfigOnly,
			&i.Labels,
			&i.Ipam,
			&i.ContainerCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedContainers = `-- name: ListOrphanedContainers :many
SELECT id, host_id, container_id, name, image_name FROM docker_containers dc
WHERE NOT EXISTS (SELECT 1 FROM hosts h WHERE h.id = dc.host_id)
`

type ListOrphanedContainersRow struct {
	ID          string `json:"id"`
	HostID      string `json:"host_id"`
	ContainerID string `json:"container_id"`
	Name        string `json:"name"`
	ImageName   string `json:"image_name"`
}

func (q *Queries) ListOrphanedContainers(ctx context.Context) ([]ListOrphanedContainersRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedContainers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedContainersRow
	for rows.Next() {
		var i ListOrphanedContainersRow
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.ContainerID,
			&i.Name,
			&i.ImageName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedImages = `-- name: ListOrphanedImages :many
SELECT id, repository, tag, image_id FROM docker_images di
WHERE NOT EXISTS (SELECT 1 FROM docker_containers dc WHERE dc.image_id = di.id)
`

type ListOrphanedImagesRow struct {
	ID         string `json:"id"`
	Repository string `json:"repository"`
	Tag        string `json:"tag"`
	ImageID    string `json:"image_id"`
}

func (q *Queries) ListOrphanedImages(ctx context.Context) ([]ListOrphanedImagesRow, error) {
	rows, err := q.db.Query(ctx, listOrphanedImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrphanedImagesRow
	for rows.Next() {
		var i ListOrphanedImagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Repository,
			&i.Tag,
			&i.ImageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVolumes = `-- name: ListVolumes :many
SELECT id, host_id, volume_id, name, driver, mountpoint, renderer, scope, labels, options, size_bytes, ref_count, created_at, updated_at, last_checked FROM docker_volumes
WHERE ($1::text IS NULL OR driver = $1)
AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
ORDER BY updated_at DESC
LIMIT $4 OFFSET $3
`

type ListVolumesParams struct {
	Driver *string `json:"driver"`
	Search *string `json:"search"`
	Offset int32   `json:"offset"`
	Limit  int32   `json:"limit"`
}

func (q *Queries) ListVolumes(ctx context.Context, arg ListVolumesParams) ([]DockerVolume, error) {
	rows, err := q.db.Query(ctx, listVolumes,
		arg.Driver,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DockerVolume
	for rows.Next() {
		var i DockerVolume
		if err := rows.Scan(
			&i.ID,
			&i.HostID,
			&i.VolumeID,
			&i.Name,
			&i.Driver,
			&i.Mountpoint,
			&i.Renderer,
			&i.Scope,
			&i.Labels,
			&i.Options,
			&i.SizeBytes,
			&i.RefCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastChecked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDockerContainer = `-- name: UpsertDockerContainer :exec
INSERT INTO docker_containers (id, host_id, container_id, name, image_id, image_name, image_tag, status, state, ports, labels, created_at, started_at, updated_at, last_checked)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (host_id, container_id) DO UPDATE SET
  name = EXCLUDED.name,
  image_id = EXCLUDED.image_id,
  image_name = EXCLUDED.image_name,
  image_tag = EXCLUDED.image_tag,
  status = EXCLUDED.status,
  state = EXCLUDED.state,
  ports = EXCLUDED.ports,
  labels = EXCLUDED.labels,
  started_at = EXCLUDED.started_at,
  updated_at = EXCLUDED.updated_at,
  last_checked = EXCLUDED.last_checked
`

type UpsertDockerContainerParams struct {
	ID          string           `json:"id"`
	HostID      string           `json:"host_id"`
	ContainerID string           `json:"container_id"`
	Name        string           `json:"name"`
	ImageID     *string          `json:"image_id"`
	ImageName   string           `json:"image_name"`
	ImageTag    string           `json:"image_tag"`
	Status      string           `json:"status"`
	State       *string          `json:"state"`
	Ports       []byte           `json:"ports"`
	Labels      []byte           `json:"labels"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	StartedAt   pgtype.Timestamp `json:"started_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
}

func (q *Queries) UpsertDockerContainer(ctx context.Context, arg UpsertDockerContainerParams) error {
	_, err := q.db.Exec(ctx, upsertDockerContainer,
		arg.ID,
		arg.HostID,
		arg.ContainerID,
		arg.Name,
		arg.ImageID,
		arg.ImageName,
		arg.ImageTag,
		arg.Status,
		arg.State,
		arg.Ports,
		arg.Labels,
		arg.CreatedAt,
		arg.StartedAt,
		arg.UpdatedAt,
		arg.LastChecked,
	)
	return err
}

const upsertDockerImage = `-- name: UpsertDockerImage :one
INSERT INTO docker_images (id, repository, tag, image_id, digest, size_bytes, source, created_at, last_checked, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (repository, tag, image_id) DO UPDATE SET
  digest = COALESCE(EXCLUDED.digest, docker_images.digest),
  size_bytes = COALESCE(EXCLUDED.size_bytes, docker_images.size_bytes),
  last_checked = EXCLUDED.last_checked,
  updated_at = EXCLUDED.updated_at
RETURNING id
`

type UpsertDockerImageParams struct {
	ID          string           `json:"id"`
	Repository  string           `json:"repository"`
	Tag         string           `json:"tag"`
	ImageID     string           `json:"image_id"`
	Digest      *string          `json:"digest"`
	SizeBytes   *int64           `json:"size_bytes"`
	Source      string           `json:"source"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertDockerImage(ctx context.Context, arg UpsertDockerImageParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertDockerImage,
		arg.ID,
		arg.Repository,
		arg.Tag,
		arg.ImageID,
		arg.Digest,
		arg.SizeBytes,
		arg.Source,
		arg.CreatedAt,
		arg.LastChecked,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertDockerImageUpdate = `-- name: UpsertDockerImageUpdate :exec
INSERT INTO docker_image_updates (id, image_id, current_tag, available_tag, is_security_update, severity, changelog_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (image_id, available_tag) DO UPDATE SET
  severity = EXCLUDED.severity,
  changelog_url = EXCLUDED.changelog_url,
  updated_at = EXCLUDED.updated_at
`

type UpsertDockerImageUpdateParams struct {
	ID               string           `json:"id"`
	ImageID          string           `json:"image_id"`
	CurrentTag       string           `json:"current_tag"`
	AvailableTag     string           `json:"available_tag"`
	IsSecurityUpdate bool             `json:"is_security_update"`
	Severity         *string          `json:"severity"`
	ChangelogUrl     *string          `json:"changelog_url"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	UpdatedAt        pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpsertDockerImageUpdate(ctx context.Context, arg UpsertDockerImageUpdateParams) error {
	_, err := q.db.Exec(ctx, upsertDockerImageUpdate,
		arg.ID,
		arg.ImageID,
		arg.CurrentTag,
		arg.AvailableTag,
		arg.IsSecurityUpdate,
		arg.Severity,
		arg.ChangelogUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertDockerNetwork = `-- name: UpsertDockerNetwork :exec
INSERT INTO docker_networks (id, host_id, network_id, name, driver, scope, ipv6_enabled, internal, attachable, ingress, config_only, labels, ipam, container_count, created_at, updated_at, last_checked)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (host_id, network_id) DO UPDATE SET
  name = EXCLUDED.name,
  driver = EXCLUDED.driver,
  scope = EXCLUDED.scope,
  ipv6_enabled = EXCLUDED.ipv6_enabled,
  internal = EXCLUDED.internal,
  attachable = EXCLUDED.attachable,
  ingress = EXCLUDED.ingress,
  config_only = EXCLUDED.config_only,
  labels = EXCLUDED.labels,
  ipam = EXCLUDED.ipam,
  container_count = EXCLUDED.container_count,
  updated_at = EXCLUDED.updated_at,
  last_checked = EXCLUDED.last_checked
`

type UpsertDockerNetworkParams struct {
	ID             string           `json:"id"`
	HostID         string           `json:"host_id"`
	NetworkID      string           `json:"network_id"`
	Name           string           `json:"name"`
	Driver         string           `json:"driver"`
	Scope          string           `json:"scope"`
	Ipv6Enabled    bool             `json:"ipv6_enabled"`
	Internal       bool             `json:"internal"`
	Attachable     bool             `json:"attachable"`
	Ingress        bool             `json:"ingress"`
	ConfigOnly     bool             `json:"config_only"`
	Labels         []byte           `json:"labels"`
	Ipam           []byte           `json:"ipam"`
	ContainerCount int32            `json:"container_count"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	LastChecked    pgtype.Timestamp `json:"last_checked"`
}

func (q *Queries) UpsertDockerNetwork(ctx context.Context, arg UpsertDockerNetworkParams) error {
	_, err := q.db.Exec(ctx, upsertDockerNetwork,
		arg.ID,
		arg.HostID,
		arg.NetworkID,
		arg.Name,
		arg.Driver,
		arg.Scope,
		arg.Ipv6Enabled,
		arg.Internal,
		arg.Attachable,
		arg.Ingress,
		arg.ConfigOnly,
		arg.Labels,
		arg.Ipam,
		arg.ContainerCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastChecked,
	)
	return err
}

const upsertDockerVolume = `-- name: UpsertDockerVolume :exec
INSERT INTO docker_volumes (id, host_id, volume_id, name, driver, mountpoint, renderer, scope, labels, options, size_bytes, ref_count, created_at, updated_at, last_checked)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (host_id, volume_id) DO UPDATE SET
  name = EXCLUDED.name,
  driver = EXCLUDED.driver,
  mountpoint = EXCLUDED.mountpoint,
  renderer = EXCLUDED.renderer,
  scope = EXCLUDED.scope,
  labels = EXCLUDED.labels,
  options = EXCLUDED.options,
  size_bytes = EXCLUDED.size_bytes,
  ref_count = EXCLUDED.ref_count,
  updated_at = EXCLUDED.updated_at,
  last_checked = EXCLUDED.last_checked
`

type UpsertDockerVolumeParams struct {
	ID          string           `json:"id"`
	HostID      string           `json:"host_id"`
	VolumeID    string           `json:"volume_id"`
	Name        string           `json:"name"`
	Driver      string           `json:"driver"`
	Mountpoint  *string          `json:"mountpoint"`
	Renderer    *string          `json:"renderer"`
	Scope       string           `json:"scope"`
	Labels      []byte           `json:"labels"`
	Options     []byte           `json:"options"`
	SizeBytes   *int64           `json:"size_bytes"`
	RefCount    int32            `json:"ref_count"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	LastChecked pgtype.Timestamp `json:"last_checked"`
}

func (q *Queries) UpsertDockerVolume(ctx context.Context, arg UpsertDockerVolumeParams) error {
	_, err := q.db.Exec(ctx, upsertDockerVolume,
		arg.ID,
		arg.HostID,
		arg.VolumeID,
		arg.Name,
		arg.Driver,
		arg.Mountpoint,
		arg.Renderer,
		arg.Scope,
		arg.Labels,
		arg.Options,
		arg.SizeBytes,
		arg.RefCount,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.LastChecked,
	)
	return err
}
