// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: host_report.sql

package db

import (
	"context"
)

const deleteHostPackagesByHostID = `-- name: DeleteHostPackagesByHostID :exec
DELETE FROM host_packages WHERE host_id = $1
`

func (q *Queries) DeleteHostPackagesByHostID(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deleteHostPackagesByHostID, hostID)
	return err
}

const getPackageByName = `-- name: GetPackageByName :one
SELECT id, name, description, category, latest_version, created_at, updated_at
FROM packages WHERE name = $1
`

func (q *Queries) GetPackageByName(ctx context.Context, name string) (Package, error) {
	row := q.db.QueryRow(ctx, getPackageByName, name)
	var i Package
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.LatestVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertHostPackage = `-- name: InsertHostPackage :exec
INSERT INTO host_packages (id, host_id, package_id, current_version, available_version, needs_update, is_security_update, source_repository_id, last_checked)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (host_id, package_id) DO UPDATE SET
    current_version = EXCLUDED.current_version,
    available_version = EXCLUDED.available_version,
    needs_update = EXCLUDED.needs_update,
    is_security_update = EXCLUDED.is_security_update,
    source_repository_id = EXCLUDED.source_repository_id,
    last_checked = NOW()
`

type InsertHostPackageParams struct {
	ID                 string  `json:"id"`
	HostID             string  `json:"host_id"`
	PackageID          string  `json:"package_id"`
	CurrentVersion     string  `json:"current_version"`
	AvailableVersion   *string `json:"available_version"`
	NeedsUpdate        bool    `json:"needs_update"`
	IsSecurityUpdate   bool    `json:"is_security_update"`
	SourceRepositoryID *string `json:"source_repository_id"`
}

func (q *Queries) InsertHostPackage(ctx context.Context, arg InsertHostPackageParams) error {
	_, err := q.db.Exec(ctx, insertHostPackage,
		arg.ID,
		arg.HostID,
		arg.PackageID,
		arg.CurrentVersion,
		arg.AvailableVersion,
		arg.NeedsUpdate,
		arg.IsSecurityUpdate,
		arg.SourceRepositoryID,
	)
	return err
}

const insertHostPackageWithWUA = `-- name: InsertHostPackageWithWUA :exec
INSERT INTO host_packages (id, host_id, package_id, current_version, available_version, needs_update, is_security_update,
    wua_guid, wua_kb, wua_severity, wua_categories, wua_description, wua_support_url, wua_revision_number, source_repository_id, last_checked)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, NOW())
ON CONFLICT (host_id, package_id) DO UPDATE SET
    current_version = EXCLUDED.current_version,
    available_version = EXCLUDED.available_version,
    needs_update = EXCLUDED.needs_update,
    is_security_update = EXCLUDED.is_security_update,
    wua_guid = EXCLUDED.wua_guid,
    wua_kb = EXCLUDED.wua_kb,
    wua_severity = EXCLUDED.wua_severity,
    wua_categories = EXCLUDED.wua_categories,
    wua_description = EXCLUDED.wua_description,
    wua_support_url = EXCLUDED.wua_support_url,
    wua_revision_number = EXCLUDED.wua_revision_number,
    source_repository_id = EXCLUDED.source_repository_id,
    last_checked = NOW()
`

type InsertHostPackageWithWUAParams struct {
	ID                 string  `json:"id"`
	HostID             string  `json:"host_id"`
	PackageID          string  `json:"package_id"`
	CurrentVersion     string  `json:"current_version"`
	AvailableVersion   *string `json:"available_version"`
	NeedsUpdate        bool    `json:"needs_update"`
	IsSecurityUpdate   bool    `json:"is_security_update"`
	WuaGuid            *string `json:"wua_guid"`
	WuaKb              *string `json:"wua_kb"`
	WuaSeverity        *string `json:"wua_severity"`
	WuaCategories      []byte  `json:"wua_categories"`
	WuaDescription     *string `json:"wua_description"`
	WuaSupportUrl      *string `json:"wua_support_url"`
	WuaRevisionNumber  *int32  `json:"wua_revision_number"`
	SourceRepositoryID *string `json:"source_repository_id"`
}

func (q *Queries) InsertHostPackageWithWUA(ctx context.Context, arg InsertHostPackageWithWUAParams) error {
	_, err := q.db.Exec(ctx, insertHostPackageWithWUA,
		arg.ID,
		arg.HostID,
		arg.PackageID,
		arg.CurrentVersion,
		arg.AvailableVersion,
		arg.NeedsUpdate,
		arg.IsSecurityUpdate,
		arg.WuaGuid,
		arg.WuaKb,
		arg.WuaSeverity,
		arg.WuaCategories,
		arg.WuaDescription,
		arg.WuaSupportUrl,
		arg.WuaRevisionNumber,
		arg.SourceRepositoryID,
	)
	return err
}

const insertPackage = `-- name: InsertPackage :one
INSERT INTO packages (id, name, description, category, latest_version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
ON CONFLICT (name) DO UPDATE SET
    latest_version = COALESCE(EXCLUDED.latest_version, packages.latest_version),
    description = COALESCE(EXCLUDED.description, packages.description),
    category = COALESCE(EXCLUDED.category, packages.category),
    updated_at = NOW()
RETURNING id
`

type InsertPackageParams struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	Description   *string `json:"description"`
	Category      *string `json:"category"`
	LatestVersion *string `json:"latest_version"`
}

func (q *Queries) InsertPackage(ctx context.Context, arg InsertPackageParams) (string, error) {
	row := q.db.QueryRow(ctx, insertPackage,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.LatestVersion,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const insertUpdateHistory = `-- name: InsertUpdateHistory :exec
INSERT INTO update_history (id, host_id, packages_count, security_count, total_packages, payload_size_kb, execution_time, timestamp, status, error_message)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW(), $8, $9)
`

type InsertUpdateHistoryParams struct {
	ID            string   `json:"id"`
	HostID        string   `json:"host_id"`
	PackagesCount int32    `json:"packages_count"`
	SecurityCount int32    `json:"security_count"`
	TotalPackages *int32   `json:"total_packages"`
	PayloadSizeKb *float64 `json:"payload_size_kb"`
	ExecutionTime *float64 `json:"execution_time"`
	Status        string   `json:"status"`
	ErrorMessage  *string  `json:"error_message"`
}

func (q *Queries) InsertUpdateHistory(ctx context.Context, arg InsertUpdateHistoryParams) error {
	_, err := q.db.Exec(ctx, insertUpdateHistory,
		arg.ID,
		arg.HostID,
		arg.PackagesCount,
		arg.SecurityCount,
		arg.TotalPackages,
		arg.PayloadSizeKb,
		arg.ExecutionTime,
		arg.Status,
		arg.ErrorMessage,
	)
	return err
}

const updateHostFromReport = `-- name: UpdateHostFromReport :exec

UPDATE hosts SET
    last_update = NOW(),
    updated_at = NOW(),
    status = CASE WHEN status = 'pending' THEN 'active' ELSE status END,
    machine_id = COALESCE($1::text, machine_id),
    os_type = COALESCE($2::text, os_type),
    os_version = COALESCE($3::text, os_version),
    hostname = COALESCE($4::text, hostname),
    ip = COALESCE($5::text, ip),
    architecture = COALESCE($6::text, architecture),
    agent_version = COALESCE($7::text, agent_version),
    cpu_model = COALESCE($8::text, cpu_model),
    cpu_cores = COALESCE($9::int, cpu_cores),
    ram_installed = COALESCE($10::double precision, ram_installed),
    swap_size = COALESCE($11::double precision, swap_size),
    disk_details = COALESCE($12::jsonb, disk_details),
    gateway_ip = $13,
    dns_servers = COALESCE($14::jsonb, dns_servers),
    network_interfaces = COALESCE($15::jsonb, network_interfaces),
    kernel_version = COALESCE($16::text, kernel_version),
    installed_kernel_version = COALESCE($17::text, installed_kernel_version),
    selinux_status = COALESCE($18::text, selinux_status),
    system_uptime = COALESCE($19::text, system_uptime),
    load_average = COALESCE($20::jsonb, load_average),
    needs_reboot = COALESCE($21::boolean, needs_reboot),
    reboot_reason = $22,
    package_manager = COALESCE($23::text, package_manager),
    awaiting_post_patch_report_run_id = NULL
WHERE id = $24
`

type UpdateHostFromReportParams struct {
	MachineID              *string  `json:"machine_id"`
	OsType                 *string  `json:"os_type"`
	OsVersion              *string  `json:"os_version"`
	Hostname               *string  `json:"hostname"`
	Ip                     *string  `json:"ip"`
	Architecture           *string  `json:"architecture"`
	AgentVersion           *string  `json:"agent_version"`
	CpuModel               *string  `json:"cpu_model"`
	CpuCores               *int32   `json:"cpu_cores"`
	RamInstalled           *float64 `json:"ram_installed"`
	SwapSize               *float64 `json:"swap_size"`
	DiskDetails            []byte   `json:"disk_details"`
	GatewayIp              *string  `json:"gateway_ip"`
	DnsServers             []byte   `json:"dns_servers"`
	NetworkInterfaces      []byte   `json:"network_interfaces"`
	KernelVersion          *string  `json:"kernel_version"`
	InstalledKernelVersion *string  `json:"installed_kernel_version"`
	SelinuxStatus          *string  `json:"selinux_status"`
	SystemUptime           *string  `json:"system_uptime"`
	LoadAverage            []byte   `json:"load_average"`
	NeedsReboot            *bool    `json:"needs_reboot"`
	RebootReason           *string  `json:"reboot_reason"`
	PackageManager         *string  `json:"package_manager"`
	ID                     string   `json:"id"`
}

// Host report/update flow (agent sends package and system info)
func (q *Queries) UpdateHostFromReport(ctx context.Context, arg UpdateHostFromReportParams) error {
	_, err := q.db.Exec(ctx, updateHostFromReport,
		arg.MachineID,
		arg.OsType,
		arg.OsVersion,
		arg.Hostname,
		arg.Ip,
		arg.Architecture,
		arg.AgentVersion,
		arg.CpuModel,
		arg.CpuCores,
		arg.RamInstalled,
		arg.SwapSize,
		arg.DiskDetails,
		arg.GatewayIp,
		arg.DnsServers,
		arg.NetworkInterfaces,
		arg.KernelVersion,
		arg.InstalledKernelVersion,
		arg.SelinuxStatus,
		arg.SystemUptime,
		arg.LoadAverage,
		arg.NeedsReboot,
		arg.RebootReason,
		arg.PackageManager,
		arg.ID,
	)
	return err
}
