// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_history.sql

package db

import (
	"context"
)

const insertJobHistory = `-- name: InsertJobHistory :exec
INSERT INTO job_history (id, job_id, queue_name, job_name, host_id, api_id, status, attempt_number, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
`

type InsertJobHistoryParams struct {
	ID            string  `json:"id"`
	JobID         string  `json:"job_id"`
	QueueName     string  `json:"queue_name"`
	JobName       string  `json:"job_name"`
	HostID        *string `json:"host_id"`
	ApiID         *string `json:"api_id"`
	Status        string  `json:"status"`
	AttemptNumber int32   `json:"attempt_number"`
}

func (q *Queries) InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) error {
	_, err := q.db.Exec(ctx, insertJobHistory,
		arg.ID,
		arg.JobID,
		arg.QueueName,
		arg.JobName,
		arg.HostID,
		arg.ApiID,
		arg.Status,
		arg.AttemptNumber,
	)
	return err
}

const listJobHistoryByApiID = `-- name: ListJobHistoryByApiID :many
SELECT id, job_id, queue_name, job_name, host_id, api_id, status, attempt_number, error_message, output, created_at, updated_at, completed_at
FROM job_history
WHERE api_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJobHistoryByApiIDParams struct {
	ApiID *string `json:"api_id"`
	Limit int32   `json:"limit"`
}

func (q *Queries) ListJobHistoryByApiID(ctx context.Context, arg ListJobHistoryByApiIDParams) ([]JobHistory, error) {
	rows, err := q.db.Query(ctx, listJobHistoryByApiID, arg.ApiID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobHistory
	for rows.Next() {
		var i JobHistory
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.QueueName,
			&i.JobName,
			&i.HostID,
			&i.ApiID,
			&i.Status,
			&i.AttemptNumber,
			&i.ErrorMessage,
			&i.Output,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobHistoryCompleted = `-- name: UpdateJobHistoryCompleted :exec
UPDATE job_history
SET status = 'completed', completed_at = NOW(), updated_at = NOW()
WHERE job_id = $1
`

func (q *Queries) UpdateJobHistoryCompleted(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, updateJobHistoryCompleted, jobID)
	return err
}

const updateJobHistoryDelayed = `-- name: UpdateJobHistoryDelayed :exec
UPDATE job_history
SET status = 'delayed', updated_at = NOW()
WHERE job_id = $1
`

func (q *Queries) UpdateJobHistoryDelayed(ctx context.Context, jobID string) error {
	_, err := q.db.Exec(ctx, updateJobHistoryDelayed, jobID)
	return err
}

const updateJobHistoryFailed = `-- name: UpdateJobHistoryFailed :exec
UPDATE job_history
SET status = 'failed', error_message = $2, completed_at = NOW(), updated_at = NOW()
WHERE job_id = $1
`

type UpdateJobHistoryFailedParams struct {
	JobID        string  `json:"job_id"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) UpdateJobHistoryFailed(ctx context.Context, arg UpdateJobHistoryFailedParams) error {
	_, err := q.db.Exec(ctx, updateJobHistoryFailed, arg.JobID, arg.ErrorMessage)
	return err
}
