// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pending_config.sql

package db

import (
	"context"
)

const deletePendingConfig = `-- name: DeletePendingConfig :exec
DELETE FROM host_pending_config WHERE host_id = $1
`

func (q *Queries) DeletePendingConfig(ctx context.Context, hostID string) error {
	_, err := q.db.Exec(ctx, deletePendingConfig, hostID)
	return err
}

const getPendingConfig = `-- name: GetPendingConfig :one
SELECT host_id, docker_enabled, compliance_enabled, compliance_on_demand_only, compliance_openscap_enabled, compliance_docker_bench_enabled, created_at, updated_at FROM host_pending_config WHERE host_id = $1
`

func (q *Queries) GetPendingConfig(ctx context.Context, hostID string) (HostPendingConfig, error) {
	row := q.db.QueryRow(ctx, getPendingConfig, hostID)
	var i HostPendingConfig
	err := row.Scan(
		&i.HostID,
		&i.DockerEnabled,
		&i.ComplianceEnabled,
		&i.ComplianceOnDemandOnly,
		&i.ComplianceOpenscapEnabled,
		&i.ComplianceDockerBenchEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPendingConfig = `-- name: UpsertPendingConfig :exec
INSERT INTO host_pending_config (
    host_id,
    docker_enabled,
    compliance_enabled,
    compliance_on_demand_only,
    compliance_openscap_enabled,
    compliance_docker_bench_enabled,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, COALESCE((SELECT created_at FROM host_pending_config WHERE host_id = $1), NOW()), NOW()
)
ON CONFLICT (host_id) DO UPDATE SET
    docker_enabled = COALESCE(EXCLUDED.docker_enabled, host_pending_config.docker_enabled),
    compliance_enabled = COALESCE(EXCLUDED.compliance_enabled, host_pending_config.compliance_enabled),
    compliance_on_demand_only = COALESCE(EXCLUDED.compliance_on_demand_only, host_pending_config.compliance_on_demand_only),
    compliance_openscap_enabled = COALESCE(EXCLUDED.compliance_openscap_enabled, host_pending_config.compliance_openscap_enabled),
    compliance_docker_bench_enabled = COALESCE(EXCLUDED.compliance_docker_bench_enabled, host_pending_config.compliance_docker_bench_enabled),
    updated_at = NOW()
`

type UpsertPendingConfigParams struct {
	HostID                       string `json:"host_id"`
	DockerEnabled                *bool  `json:"docker_enabled"`
	ComplianceEnabled            *bool  `json:"compliance_enabled"`
	ComplianceOnDemandOnly       *bool  `json:"compliance_on_demand_only"`
	ComplianceOpenscapEnabled    *bool  `json:"compliance_openscap_enabled"`
	ComplianceDockerBenchEnabled *bool  `json:"compliance_docker_bench_enabled"`
}

func (q *Queries) UpsertPendingConfig(ctx context.Context, arg UpsertPendingConfigParams) error {
	_, err := q.db.Exec(ctx, upsertPendingConfig,
		arg.HostID,
		arg.DockerEnabled,
		arg.ComplianceEnabled,
		arg.ComplianceOnDemandOnly,
		arg.ComplianceOpenscapEnabled,
		arg.ComplianceDockerBenchEnabled,
	)
	return err
}
