// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApprovePatchRun(ctx context.Context, id string) error
	CountActiveAdmins(ctx context.Context) (int64, error)
	CountActiveRepositories(ctx context.Context) (int32, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountComplianceResultsByScan(ctx context.Context, arg CountComplianceResultsByScanParams) (int64, error)
	CountComplianceScansByHost(ctx context.Context, hostID string) (int64, error)
	CountComplianceScansHistory(ctx context.Context, arg CountComplianceScansHistoryParams) (int64, error)
	CountContainers(ctx context.Context, arg CountContainersParams) (int32, error)
	CountContainersByImageID(ctx context.Context, imageID *string) (int32, error)
	// Dashboard stats
	CountDockerHosts(ctx context.Context) (int32, error)
	CountEnabledHostRepositories(ctx context.Context) (int32, error)
	CountHosts(ctx context.Context) (int64, error)
	CountHostsForPackage(ctx context.Context, arg CountHostsForPackageParams) (int32, error)
	CountImages(ctx context.Context, arg CountImagesParams) (int32, error)
	CountNetworks(ctx context.Context, arg CountNetworksParams) (int32, error)
	CountNetworksByHostID(ctx context.Context, hostID string) (int32, error)
	CountPackages(ctx context.Context, arg CountPackagesParams) (int32, error)
	CountPatchRuns(ctx context.Context, arg CountPatchRunsParams) (int64, error)
	CountPatchRunsTotal(ctx context.Context) (int64, error)
	CountRepositories(ctx context.Context) (int32, error)
	CountSecureRepositories(ctx context.Context) (int32, error)
	CountSuperadmins(ctx context.Context) (int64, error)
	CountTfaRememberSessionsByUser(ctx context.Context, userID string) (int64, error)
	CountUnscannedHosts(ctx context.Context) (int64, error)
	CountUpdateHistory(ctx context.Context, hostID string) (int32, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CountVolumes(ctx context.Context, arg CountVolumesParams) (int32, error)
	CountVolumesByHostID(ctx context.Context, hostID string) (int32, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	CreateAutoEnrollmentToken(ctx context.Context, arg CreateAutoEnrollmentTokenParams) error
	CreateComplianceProfile(ctx context.Context, arg CreateComplianceProfileParams) (ComplianceProfile, error)
	CreateComplianceResult(ctx context.Context, arg CreateComplianceResultParams) (ComplianceResult, error)
	CreateComplianceRule(ctx context.Context, arg CreateComplianceRuleParams) (ComplianceRule, error)
	CreateComplianceScan(ctx context.Context, arg CreateComplianceScanParams) (ComplianceScan, error)
	CreateDiscordUser(ctx context.Context, arg CreateDiscordUserParams) error
	CreateHost(ctx context.Context, arg CreateHostParams) error
	CreateHostGroup(ctx context.Context, arg CreateHostGroupParams) error
	CreateOidcUser(ctx context.Context, arg CreateOidcUserParams) error
	CreatePatchPolicy(ctx context.Context, arg CreatePatchPolicyParams) error
	CreatePatchPolicyAssignment(ctx context.Context, arg CreatePatchPolicyAssignmentParams) error
	CreatePatchPolicyExclusion(ctx context.Context, arg CreatePatchPolicyExclusionParams) error
	// patch_runs
	CreatePatchRun(ctx context.Context, arg CreatePatchRunParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAlert(ctx context.Context, id string) error
	DeleteAlertsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteAutoEnrollmentToken(ctx context.Context, id string) error
	DeleteComplianceResultsByScan(ctx context.Context, scanID string) error
	DeleteContainer(ctx context.Context, id string) error
	DeleteContainersByIDs(ctx context.Context, dollar_1 []string) error
	DeleteDashboardPreferencesByUserID(ctx context.Context, userID string) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteHost(ctx context.Context, id string) error
	DeleteHostGroup(ctx context.Context, id string) error
	DeleteHostGroupMemberships(ctx context.Context, hostID string) error
	DeleteHostPackagesByHostID(ctx context.Context, hostID string) error
	DeleteHostRepositoriesByHostID(ctx context.Context, hostID string) error
	DeleteHostsByIDs(ctx context.Context, dollar_1 []string) error
	DeleteImageByID(ctx context.Context, id string) error
	DeleteImageUpdatesByImageID(ctx context.Context, imageID string) error
	DeleteImagesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteNetwork(ctx context.Context, id string) error
	DeleteOldestTfaRememberSession(ctx context.Context, userID string) error
	DeletePackagesByIDs(ctx context.Context, dollar_1 []string) error
	DeletePatchPolicy(ctx context.Context, id string) error
	DeletePatchPolicyAssignment(ctx context.Context, id string) error
	DeletePatchPolicyExclusion(ctx context.Context, arg DeletePatchPolicyExclusionParams) error
	DeletePendingConfig(ctx context.Context, hostID string) error
	DeleteRepositoriesByIDs(ctx context.Context, dollar_1 []string) error
	DeleteRepository(ctx context.Context, id string) error
	DeleteRolePermissions(ctx context.Context, role string) error
	DeleteRunningComplianceScansByHost(ctx context.Context, hostID string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteVolume(ctx context.Context, id string) error
	DisableTfa(ctx context.Context, id string) error
	ExistsByUsernameOrEmail(ctx context.Context, arg ExistsByUsernameOrEmailParams) (bool, error)
	ExistsPatchPolicyExclusion(ctx context.Context, arg ExistsPatchPolicyExclusionParams) (bool, error)
	FindSessionByUserAndDevice(ctx context.Context, arg FindSessionByUserAndDeviceParams) (UserSession, error)
	FindSessionByUserAndDeviceID(ctx context.Context, arg FindSessionByUserAndDeviceIDParams) (UserSession, error)
	FindSessionWithTfaBypass(ctx context.Context, arg FindSessionWithTfaBypassParams) (FindSessionWithTfaBypassRow, error)
	GetAcceptedVersionsByUserID(ctx context.Context, userID string) ([]string, error)
	GetAlertActionByName(ctx context.Context, name string) (AlertAction, error)
	GetAlertByID(ctx context.Context, id string) (GetAlertByIDRow, error)
	GetAlertConfigByType(ctx context.Context, alertType string) (GetAlertConfigByTypeRow, error)
	GetAlertStatsBySeverity(ctx context.Context) ([]GetAlertStatsBySeverityRow, error)
	GetAlertsForCleanup(ctx context.Context, arg GetAlertsForCleanupParams) ([]GetAlertsForCleanupRow, error)
	GetAlertsToAutoResolve(ctx context.Context, arg GetAlertsToAutoResolveParams) ([]GetAlertsToAutoResolveRow, error)
	GetAutoEnrollmentTokenByID(ctx context.Context, id string) (GetAutoEnrollmentTokenByIDRow, error)
	GetAutoEnrollmentTokenByKey(ctx context.Context, tokenKey string) (AutoEnrollmentToken, error)
	GetAutoEnrollmentTokenRaw(ctx context.Context, id string) (AutoEnrollmentToken, error)
	GetCategories(ctx context.Context) ([]*string, error)
	GetComplianceProfileByID(ctx context.Context, id string) (ComplianceProfile, error)
	GetComplianceProfileByName(ctx context.Context, name string) (ComplianceProfile, error)
	GetComplianceResultSeverityBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultSeverityBreakdownRow, error)
	GetComplianceResultSeverityBreakdownForScans(ctx context.Context, dollar_1 []string) ([]GetComplianceResultSeverityBreakdownForScansRow, error)
	GetComplianceResultStatusBreakdown(ctx context.Context, scanID string) ([]GetComplianceResultStatusBreakdownRow, error)
	GetComplianceResultsForRuleFromScans(ctx context.Context, arg GetComplianceResultsForRuleFromScansParams) ([]GetComplianceResultsForRuleFromScansRow, error)
	GetComplianceRuleByID(ctx context.Context, id string) (GetComplianceRuleByIDRow, error)
	GetComplianceRuleByProfileAndRef(ctx context.Context, arg GetComplianceRuleByProfileAndRefParams) (ComplianceRule, error)
	GetComplianceScanByID(ctx context.Context, id string) (GetComplianceScanByIDRow, error)
	GetComplianceScansForTrends(ctx context.Context, arg GetComplianceScansForTrendsParams) ([]GetComplianceScansForTrendsRow, error)
	// Containers
	GetContainerByID(ctx context.Context, id string) (DockerContainer, error)
	GetContainerCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetContainerCountsByImageIDsRow, error)
	GetContainersByHostID(ctx context.Context, hostID string) ([]DockerContainer, error)
	GetContainersByImageID(ctx context.Context, arg GetContainersByImageIDParams) ([]DockerContainer, error)
	GetContainersByImageIDAll(ctx context.Context, imageID *string) ([]DockerContainer, error)
	GetContainersByStatus(ctx context.Context) ([]GetContainersByStatusRow, error)
	GetDashboardLayout(ctx context.Context, userID string) (DashboardLayout, error)
	GetDashboardStats(ctx context.Context, arg GetDashboardStatsParams) (GetDashboardStatsRow, error)
	// patch_policy_assignments
	GetDirectPatchPolicyAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	// Hosts (include hosts with containers, volumes, or networks)
	GetDistinctDockerHostIDs(ctx context.Context) ([]string, error)
	GetDockerDashboardStats(ctx context.Context) (GetDockerDashboardStatsRow, error)
	GetDockerHostsByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsByIDsRow, error)
	GetDockerHostsMinimalByIDs(ctx context.Context, dollar_1 []string) ([]GetDockerHostsMinimalByIDsRow, error)
	GetFirstComplianceProfileByType(ctx context.Context, type_ string) (ComplianceProfile, error)
	GetFirstSettings(ctx context.Context) (Setting, error)
	GetHomepageStats(ctx context.Context, since pgtype.Timestamp) (GetHomepageStatsRow, error)
	GetHostByApiID(ctx context.Context, apiID string) (Host, error)
	GetHostByID(ctx context.Context, id string) (Host, error)
	GetHostCountsForRepos(ctx context.Context, dollar_1 []string) ([]GetHostCountsForReposRow, error)
	GetHostDockerStats(ctx context.Context, hostID string) (GetHostDockerStatsRow, error)
	GetHostGroupByID(ctx context.Context, id string) (HostGroup, error)
	GetHostGroupMemberships(ctx context.Context, hostID string) ([]string, error)
	GetHostGroupsForHosts(ctx context.Context, dollar_1 []string) ([]GetHostGroupsForHostsRow, error)
	GetHostIDsByGroup(ctx context.Context, hostGroupID string) ([]string, error)
	GetHostIDsByGroupIDs(ctx context.Context, dollar_1 []string) ([]string, error)
	GetHostPackageStats(ctx context.Context, hostID string) (GetHostPackageStatsRow, error)
	GetHostPackageStatsByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostPackageStatsByHostIDsRow, error)
	GetHostPackageStatsByPackageIDs(ctx context.Context, arg GetHostPackageStatsByPackageIDsParams) ([]GetHostPackageStatsByPackageIDsRow, error)
	GetHostPackagesForScopedApi(ctx context.Context, hostID string) ([]GetHostPackagesForScopedApiRow, error)
	GetHostPackagesWithHostsByPackageID(ctx context.Context, packageID string) ([]GetHostPackagesWithHostsByPackageIDRow, error)
	GetHostPackagesWithPackages(ctx context.Context, hostID string) ([]GetHostPackagesWithPackagesRow, error)
	GetHostRefsForPackageIDs(ctx context.Context, arg GetHostRefsForPackageIDsParams) ([]GetHostRefsForPackageIDsRow, error)
	GetHostRepositoriesByHostID(ctx context.Context, hostID string) ([]GetHostRepositoriesByHostIDRow, error)
	GetHostRepositoriesForRepo(ctx context.Context, repositoryID string) ([]GetHostRepositoriesForRepoRow, error)
	GetHostRepositoryCountByHostIDs(ctx context.Context, dollar_1 []string) ([]GetHostRepositoryCountByHostIDsRow, error)
	GetHostsByIDs(ctx context.Context, dollar_1 []string) ([]Host, error)
	GetHostsForPackageTrends(ctx context.Context) ([]GetHostsForPackageTrendsRow, error)
	GetHostsWithCounts(ctx context.Context, arg GetHostsWithCountsParams) ([]GetHostsWithCountsRow, error)
	// Images
	GetImageByID(ctx context.Context, id string) (DockerImage, error)
	GetImageIDByRepositoryTagImageID(ctx context.Context, arg GetImageIDByRepositoryTagImageIDParams) (string, error)
	GetImageUpdatesByImageID(ctx context.Context, imageID string) ([]DockerImageUpdate, error)
	GetImagesByIDs(ctx context.Context, dollar_1 []string) ([]DockerImage, error)
	GetImagesBySource(ctx context.Context) ([]GetImagesBySourceRow, error)
	GetLatestAlertHistoryForAlerts(ctx context.Context, dollar_1 []string) ([]GetLatestAlertHistoryForAlertsRow, error)
	GetLatestCompletedScans(ctx context.Context) ([]GetLatestCompletedScansRow, error)
	GetLatestCompletedScansByProfile(ctx context.Context, profileID string) ([]GetLatestCompletedScansByProfileRow, error)
	GetLatestComplianceScanByHost(ctx context.Context, hostID string) (GetLatestComplianceScanByHostRow, error)
	GetLatestSystemStatistics(ctx context.Context) (GetLatestSystemStatisticsRow, error)
	// Networks
	GetNetworkByID(ctx context.Context, id string) (DockerNetwork, error)
	GetNetworksByHostID(ctx context.Context, hostID string) ([]DockerNetwork, error)
	GetOSDistribution(ctx context.Context) ([]GetOSDistributionRow, error)
	GetOSDistributionByTypeAndVersion(ctx context.Context) ([]GetOSDistributionByTypeAndVersionRow, error)
	GetPackageByID(ctx context.Context, id string) (Package, error)
	GetPackageByName(ctx context.Context, name string) (Package, error)
	GetPatchPolicyAssignmentByID(ctx context.Context, id string) (PatchPolicyAssignment, error)
	GetPatchPolicyByGroupAssignment(ctx context.Context, targetID string) (PatchPolicy, error)
	GetPatchPolicyByID(ctx context.Context, id string) (PatchPolicy, error)
	GetPatchRunByID(ctx context.Context, id string) (GetPatchRunByIDRow, error)
	GetPatchRunByIDSimple(ctx context.Context, id string) (PatchRun, error)
	GetPendingConfig(ctx context.Context, hostID string) (HostPendingConfig, error)
	GetRecentComplianceScans(ctx context.Context) ([]GetRecentComplianceScansRow, error)
	GetRecentHosts(ctx context.Context, limit int32) ([]GetRecentHostsRow, error)
	GetRecentUsers(ctx context.Context, limit int32) ([]GetRecentUsersRow, error)
	GetRepositoryByID(ctx context.Context, id string) (Repository, error)
	GetRepositoryByURLDistComponents(ctx context.Context, arg GetRepositoryByURLDistComponentsParams) (Repository, error)
	GetRepositoryForDelete(ctx context.Context, id string) (GetRepositoryForDeleteRow, error)
	GetRolePermissions(ctx context.Context, role string) (RolePermission, error)
	GetSecurityCountByPackageIDs(ctx context.Context, arg GetSecurityCountByPackageIDsParams) ([]GetSecurityCountByPackageIDsRow, error)
	GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (UserSession, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetSystemStatisticsDaily(ctx context.Context, arg GetSystemStatisticsDailyParams) ([]GetSystemStatisticsDailyRow, error)
	GetSystemStatsForInsert(ctx context.Context) (GetSystemStatsForInsertRow, error)
	GetUpdateCountsByImageIDs(ctx context.Context, dollar_1 []string) ([]GetUpdateCountsByImageIDsRow, error)
	GetUpdateHistory(ctx context.Context, arg GetUpdateHistoryParams) ([]UpdateHistory, error)
	GetUpdateHistoryDaily(ctx context.Context, arg GetUpdateHistoryDailyParams) ([]GetUpdateHistoryDailyRow, error)
	GetUpdateTrends(ctx context.Context, timestamp pgtype.Timestamp) ([]GetUpdateTrendsRow, error)
	GetUpdatesCountByPackageIDs(ctx context.Context, arg GetUpdatesCountByPackageIDsParams) ([]GetUpdatesCountByPackageIDsRow, error)
	GetUserByDiscordID(ctx context.Context, discordID *string) (User, error)
	GetUserByDiscordIDOrEmail(ctx context.Context, arg GetUserByDiscordIDOrEmailParams) (User, error)
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByOidcSub(ctx context.Context, oidcSub *string) (User, error)
	GetUserByOidcSubOrEmail(ctx context.Context, arg GetUserByOidcSubOrEmailParams) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetUserByUsernameOrEmail(ctx context.Context, lower string) (User, error)
	// Volumes
	GetVolumeByID(ctx context.Context, id string) (DockerVolume, error)
	GetVolumesByHostID(ctx context.Context, hostID string) ([]DockerVolume, error)
	IncrementAutoEnrollmentHostsCreated(ctx context.Context, id string) error
	InsertAlertHistory(ctx context.Context, arg InsertAlertHistoryParams) (AlertHistory, error)
	InsertDashboardPreference(ctx context.Context, arg InsertDashboardPreferenceParams) error
	InsertHostGroupMembership(ctx context.Context, arg InsertHostGroupMembershipParams) error
	InsertHostPackage(ctx context.Context, arg InsertHostPackageParams) error
	InsertHostRepository(ctx context.Context, arg InsertHostRepositoryParams) error
	InsertJobHistory(ctx context.Context, arg InsertJobHistoryParams) error
	InsertPackage(ctx context.Context, arg InsertPackageParams) (string, error)
	InsertReleaseNotesAcceptance(ctx context.Context, arg InsertReleaseNotesAcceptanceParams) (string, error)
	InsertRepository(ctx context.Context, arg InsertRepositoryParams) (Repository, error)
	InsertSystemStatistics(ctx context.Context, arg InsertSystemStatisticsParams) error
	InsertUpdateHistory(ctx context.Context, arg InsertUpdateHistoryParams) error
	ListActiveAlertsByType(ctx context.Context, type_ string) ([]ListActiveAlertsByTypeRow, error)
	ListActiveComplianceScans(ctx context.Context) ([]ListActiveComplianceScansRow, error)
	ListActivePatchRuns(ctx context.Context) ([]ListActivePatchRunsRow, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAlertActions(ctx context.Context) ([]AlertAction, error)
	ListAlertConfig(ctx context.Context) ([]ListAlertConfigRow, error)
	ListAlertHistoryByAlertID(ctx context.Context, alertID string) ([]ListAlertHistoryByAlertIDRow, error)
	ListAlerts(ctx context.Context) ([]ListAlertsRow, error)
	ListAlertsAssignedTo(ctx context.Context, assignedToUserID *string) ([]ListAlertsAssignedToRow, error)
	ListAutoEnrollmentTokens(ctx context.Context) ([]ListAutoEnrollmentTokensRow, error)
	ListComplianceProfiles(ctx context.Context) ([]ComplianceProfile, error)
	ListComplianceResultsByScan(ctx context.Context, arg ListComplianceResultsByScanParams) ([]ListComplianceResultsByScanRow, error)
	ListComplianceRulesByProfile(ctx context.Context, profileID string) ([]ComplianceRule, error)
	ListComplianceScansByHost(ctx context.Context, arg ListComplianceScansByHostParams) ([]ListComplianceScansByHostRow, error)
	ListComplianceScansHistory(ctx context.Context, arg ListComplianceScansHistoryParams) ([]ListComplianceScansHistoryRow, error)
	ListContainers(ctx context.Context, arg ListContainersParams) ([]DockerContainer, error)
	ListDashboardPreferencesByUserID(ctx context.Context, userID string) ([]DashboardPreference, error)
	ListDockerHostsPaginated(ctx context.Context, arg ListDockerHostsPaginatedParams) ([]ListDockerHostsPaginatedRow, error)
	ListHostGroups(ctx context.Context) ([]HostGroup, error)
	ListHostGroupsWithHostCount(ctx context.Context) ([]ListHostGroupsWithHostCountRow, error)
	ListHosts(ctx context.Context) ([]Host, error)
	ListHostsForComplianceDashboard(ctx context.Context) ([]ListHostsForComplianceDashboardRow, error)
	ListHostsForPackage(ctx context.Context, arg ListHostsForPackageParams) ([]ListHostsForPackageRow, error)
	ListHostsPaginated(ctx context.Context, arg ListHostsPaginatedParams) ([]ListHostsPaginatedRow, error)
	ListImages(ctx context.Context, arg ListImagesParams) ([]DockerImage, error)
	ListJobHistoryByApiID(ctx context.Context, arg ListJobHistoryByApiIDParams) ([]JobHistory, error)
	ListNeedingUpdates(ctx context.Context) ([]ListNeedingUpdatesRow, error)
	ListNetworks(ctx context.Context, arg ListNetworksParams) ([]DockerNetwork, error)
	ListOrphanedContainers(ctx context.Context) ([]ListOrphanedContainersRow, error)
	ListOrphanedImages(ctx context.Context) ([]ListOrphanedImagesRow, error)
	ListOrphanedPackages(ctx context.Context) ([]ListOrphanedPackagesRow, error)
	ListOrphanedRepositories(ctx context.Context) ([]ListOrphanedRepositoriesRow, error)
	ListPackages(ctx context.Context, arg ListPackagesParams) ([]ListPackagesRow, error)
	// patch_policies
	ListPatchPolicies(ctx context.Context) ([]PatchPolicy, error)
	ListPatchPolicyAssignments(ctx context.Context, arg ListPatchPolicyAssignmentsParams) ([]PatchPolicyAssignment, error)
	ListPatchPolicyAssignmentsByPolicy(ctx context.Context, patchPolicyID string) ([]PatchPolicyAssignment, error)
	// patch_policy_exclusions
	ListPatchPolicyExclusions(ctx context.Context, patchPolicyID string) ([]ListPatchPolicyExclusionsRow, error)
	ListPatchRuns(ctx context.Context, arg ListPatchRunsParams) ([]ListPatchRunsRow, error)
	ListPatchRunsByPackage(ctx context.Context, arg ListPatchRunsByPackageParams) ([]ListPatchRunsByPackageRow, error)
	ListPatchRunsByStatus(ctx context.Context) ([]ListPatchRunsByStatusRow, error)
	ListPatchRunsOrderByCompletedAt(ctx context.Context, arg ListPatchRunsOrderByCompletedAtParams) ([]ListPatchRunsOrderByCompletedAtRow, error)
	ListPatchRunsOrderByCompletedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCompletedAtAscParams) ([]ListPatchRunsOrderByCompletedAtAscRow, error)
	ListPatchRunsOrderByCreatedAtAsc(ctx context.Context, arg ListPatchRunsOrderByCreatedAtAscParams) ([]ListPatchRunsOrderByCreatedAtAscRow, error)
	ListPatchRunsOrderByStartedAt(ctx context.Context, arg ListPatchRunsOrderByStartedAtParams) ([]ListPatchRunsOrderByStartedAtRow, error)
	ListPatchRunsOrderByStartedAtAsc(ctx context.Context, arg ListPatchRunsOrderByStartedAtAscParams) ([]ListPatchRunsOrderByStartedAtAscRow, error)
	ListPatchRunsOrderByStatus(ctx context.Context, arg ListPatchRunsOrderByStatusParams) ([]ListPatchRunsOrderByStatusRow, error)
	ListPatchRunsOrderByStatusDesc(ctx context.Context, arg ListPatchRunsOrderByStatusDescParams) ([]ListPatchRunsOrderByStatusDescRow, error)
	ListRecentPatchRuns(ctx context.Context, limit int32) ([]ListRecentPatchRunsRow, error)
	ListRepositories(ctx context.Context, arg ListRepositoriesParams) ([]Repository, error)
	ListRoles(ctx context.Context) ([]RolePermission, error)
	ListSessionsByUserID(ctx context.Context, userID string) ([]UserSession, error)
	ListStalledComplianceScans(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansRow, error)
	ListStalledComplianceScansWithDetails(ctx context.Context, startedAt pgtype.Timestamp) ([]ListStalledComplianceScansWithDetailsRow, error)
	ListSystemStatisticsByDateRange(ctx context.Context, arg ListSystemStatisticsByDateRangeParams) ([]SystemStatistic, error)
	ListUpdateHistoryByDateRange(ctx context.Context, arg ListUpdateHistoryByDateRangeParams) ([]UpdateHistory, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVolumes(ctx context.Context, arg ListVolumesParams) ([]DockerVolume, error)
	RevokeAllSessionsForUser(ctx context.Context, userID string) error
	RevokeAllSessionsForUserExcept(ctx context.Context, arg RevokeAllSessionsForUserExceptParams) error
	RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error
	ToggleHostRepository(ctx context.Context, arg ToggleHostRepositoryParams) error
	UpdateAlert(ctx context.Context, id string) error
	UpdateAlertAssignment(ctx context.Context, arg UpdateAlertAssignmentParams) error
	UpdateAlertResolved(ctx context.Context, arg UpdateAlertResolvedParams) error
	UpdateAlertUnassign(ctx context.Context, id string) error
	UpdateAlertUnresolve(ctx context.Context, id string) error
	UpdateAutoEnrollmentToken(ctx context.Context, arg UpdateAutoEnrollmentTokenParams) error
	UpdateAutoEnrollmentTokenLastUsedAt(ctx context.Context, id string) error
	UpdateComplianceRule(ctx context.Context, arg UpdateComplianceRuleParams) error
	UpdateHostApiCredentials(ctx context.Context, arg UpdateHostApiCredentialsParams) error
	UpdateHostAutoUpdate(ctx context.Context, arg UpdateHostAutoUpdateParams) error
	UpdateHostComplianceEnabled(ctx context.Context, arg UpdateHostComplianceEnabledParams) error
	UpdateHostComplianceMode(ctx context.Context, arg UpdateHostComplianceModeParams) error
	UpdateHostComplianceScannerStatus(ctx context.Context, arg UpdateHostComplianceScannerStatusParams) error
	UpdateHostComplianceScanners(ctx context.Context, arg UpdateHostComplianceScannersParams) error
	UpdateHostConnection(ctx context.Context, arg UpdateHostConnectionParams) error
	UpdateHostDockerEnabled(ctx context.Context, arg UpdateHostDockerEnabledParams) error
	UpdateHostDownAlerts(ctx context.Context, arg UpdateHostDownAlertsParams) error
	UpdateHostFriendlyName(ctx context.Context, arg UpdateHostFriendlyNameParams) error
	// Host report/update flow (agent sends package and system info)
	UpdateHostFromReport(ctx context.Context, arg UpdateHostFromReportParams) error
	UpdateHostGroup(ctx context.Context, arg UpdateHostGroupParams) error
	UpdateHostNotes(ctx context.Context, arg UpdateHostNotesParams) error
	UpdateHostPing(ctx context.Context, id string) error
	UpdateHostPrimaryInterface(ctx context.Context, arg UpdateHostPrimaryInterfaceParams) error
	UpdateJobHistoryCompleted(ctx context.Context, jobID string) error
	UpdateJobHistoryDelayed(ctx context.Context, jobID string) error
	UpdateJobHistoryFailed(ctx context.Context, arg UpdateJobHistoryFailedParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePatchPolicy(ctx context.Context, arg UpdatePatchPolicyParams) error
	UpdatePatchRunCompleted(ctx context.Context, arg UpdatePatchRunCompletedParams) error
	UpdatePatchRunFailed(ctx context.Context, arg UpdatePatchRunFailedParams) error
	UpdatePatchRunPackagesAffected(ctx context.Context, arg UpdatePatchRunPackagesAffectedParams) error
	UpdatePatchRunProgress(ctx context.Context, arg UpdatePatchRunProgressParams) error
	UpdatePatchRunStarted(ctx context.Context, id string) error
	UpdatePatchRunStatus(ctx context.Context, arg UpdatePatchRunStatusParams) error
	UpdatePatchRunValidated(ctx context.Context, arg UpdatePatchRunValidatedParams) error
	UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) error
	UpdateSessionActivity(ctx context.Context, id string) error
	UpdateSessionOnLogin(ctx context.Context, arg UpdateSessionOnLoginParams) error
	UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error
	UpdateSettingsConfig(ctx context.Context, arg UpdateSettingsConfigParams) error
	UpdateStalledComplianceScans(ctx context.Context, arg UpdateStalledComplianceScansParams) error
	UpdateTfaBackupCodes(ctx context.Context, arg UpdateTfaBackupCodesParams) error
	UpdateTfaEnabled(ctx context.Context, arg UpdateTfaEnabledParams) error
	UpdateTfaSecret(ctx context.Context, arg UpdateTfaSecretParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserDiscordLink(ctx context.Context, arg UpdateUserDiscordLinkParams) error
	UpdateUserDiscordProfile(ctx context.Context, arg UpdateUserDiscordProfileParams) error
	UpdateUserDiscordUnlink(ctx context.Context, id string) error
	UpdateUserOidcLink(ctx context.Context, arg UpdateUserOidcLinkParams) error
	UpdateUserOidcProfile(ctx context.Context, arg UpdateUserOidcProfileParams) error
	UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error
	UpsertAlertConfig(ctx context.Context, arg UpsertAlertConfigParams) (AlertConfig, error)
	UpsertDashboardLayout(ctx context.Context, arg UpsertDashboardLayoutParams) error
	UpsertDockerContainer(ctx context.Context, arg UpsertDockerContainerParams) error
	UpsertDockerImage(ctx context.Context, arg UpsertDockerImageParams) (string, error)
	UpsertDockerImageUpdate(ctx context.Context, arg UpsertDockerImageUpdateParams) error
	UpsertDockerNetwork(ctx context.Context, arg UpsertDockerNetworkParams) error
	UpsertDockerVolume(ctx context.Context, arg UpsertDockerVolumeParams) error
	UpsertPendingConfig(ctx context.Context, arg UpsertPendingConfigParams) error
	UpsertRolePermissions(ctx context.Context, arg UpsertRolePermissionsParams) (RolePermission, error)
}

var _ Querier = (*Queries)(nil)
