// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: release_notes_acceptances.sql

package db

import (
	"context"
)

const getAcceptedVersionsByUserID = `-- name: GetAcceptedVersionsByUserID :many
SELECT version FROM release_notes_acceptances WHERE user_id = $1
`

func (q *Queries) GetAcceptedVersionsByUserID(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getAcceptedVersionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var version string
		if err := rows.Scan(&version); err != nil {
			return nil, err
		}
		items = append(items, version)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertReleaseNotesAcceptance = `-- name: InsertReleaseNotesAcceptance :one
INSERT INTO release_notes_acceptances (user_id, version)
VALUES ($1, $2)
RETURNING id
`

type InsertReleaseNotesAcceptanceParams struct {
	UserID  string `json:"user_id"`
	Version string `json:"version"`
}

func (q *Queries) InsertReleaseNotesAcceptance(ctx context.Context, arg InsertReleaseNotesAcceptanceParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReleaseNotesAcceptance, arg.UserID, arg.Version)
	var id string
	err := row.Scan(&id)
	return id, err
}
