// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: search.sql

package db

import (
	"context"
)

const globalSearch = `-- name: GlobalSearch :many
WITH host_results AS (
    SELECT
        id,
        COALESCE(friendly_name, hostname, '') AS name,
        'host'::text AS type,
        COALESCE(os_type || ' ' || os_version, '') AS description
    FROM hosts
    WHERE friendly_name ILIKE '%' || $1::text || '%'
       OR hostname ILIKE '%' || $1::text || '%'
       OR ip ILIKE '%' || $1::text || '%'
       OR notes ILIKE '%' || $1::text || '%'
    ORDER BY last_update DESC NULLS LAST
    LIMIT 5
),
package_results AS (
    SELECT
        id,
        name,
        'package'::text AS type,
        COALESCE(description, category, '') AS description
    FROM packages
    WHERE name ILIKE '%' || $1::text || '%'
    ORDER BY name ASC
    LIMIT 5
),
repository_results AS (
    SELECT
        id,
        name,
        'repository'::text AS type,
        COALESCE(url, '') AS description
    FROM repositories
    WHERE name ILIKE '%' || $1::text || '%'
       OR url ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%'
    ORDER BY name ASC
    LIMIT 5
),
host_group_results AS (
    SELECT
        id,
        name,
        'host_group'::text AS type,
        COALESCE(description, '') AS description
    FROM host_groups
    WHERE name ILIKE '%' || $1::text || '%'
       OR description ILIKE '%' || $1::text || '%'
    ORDER BY name ASC
    LIMIT 5
),
user_results AS (
    SELECT
        id,
        username AS name,
        'user'::text AS type,
        COALESCE(email, '') || CASE WHEN first_name IS NOT NULL OR last_name IS NOT NULL
            THEN ' - ' || COALESCE(first_name, '') || ' ' || COALESCE(last_name, '')
            ELSE '' END AS description
    FROM users
    WHERE username ILIKE '%' || $1::text || '%'
       OR email ILIKE '%' || $1::text || '%'
       OR first_name ILIKE '%' || $1::text || '%'
       OR last_name ILIKE '%' || $1::text || '%'
    ORDER BY username ASC
    LIMIT 5
),
docker_container_results AS (
    SELECT
        id,
        name,
        'docker_container'::text AS type,
        image_name || ':' || image_tag || ' (' || status || ')' AS description
    FROM docker_containers
    WHERE name ILIKE '%' || $1::text || '%'
       OR image_name ILIKE '%' || $1::text || '%'
       OR container_id ILIKE '%' || $1::text || '%'
    ORDER BY name ASC
    LIMIT 5
),
docker_image_results AS (
    SELECT
        id,
        repository || ':' || tag AS name,
        'docker_image'::text AS type,
        COALESCE(source, '') AS description
    FROM docker_images
    WHERE repository ILIKE '%' || $1::text || '%'
       OR tag ILIKE '%' || $1::text || '%'
       OR image_id ILIKE '%' || $1::text || '%'
    ORDER BY repository ASC
    LIMIT 5
)
SELECT id, name, type, description FROM host_results
UNION ALL
SELECT id, name, type, description FROM package_results
UNION ALL
SELECT id, name, type, description FROM repository_results
UNION ALL
SELECT id, name, type, description FROM host_group_results
UNION ALL
SELECT id, name, type, description FROM user_results
UNION ALL
SELECT id, name, type, description FROM docker_container_results
UNION ALL
SELECT id, name, type, description FROM docker_image_results
LIMIT 30
`

type GlobalSearchRow struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Type        string      `json:"type"`
	Description interface{} `json:"description"`
}

func (q *Queries) GlobalSearch(ctx context.Context, search string) ([]GlobalSearchRow, error) {
	rows, err := q.db.Query(ctx, globalSearch, search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalSearchRow
	for rows.Next() {
		var i GlobalSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
