// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTfaRememberSessionsByUser = `-- name: CountTfaRememberSessionsByUser :one
SELECT COUNT(*) FROM user_sessions
WHERE user_id = $1 AND tfa_remember_me = true AND is_revoked = false AND expires_at > NOW()
`

func (q *Queries) CountTfaRememberSessionsByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTfaRememberSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO user_sessions (
    id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, false, $12, $13, 1, $14)
`

type CreateSessionParams struct {
	ID                string           `json:"id"`
	UserID            string           `json:"user_id"`
	RefreshToken      string           `json:"refresh_token"`
	AccessTokenHash   *string          `json:"access_token_hash"`
	IpAddress         *string          `json:"ip_address"`
	UserAgent         *string          `json:"user_agent"`
	DeviceFingerprint *string          `json:"device_fingerprint"`
	DeviceID          *string          `json:"device_id"`
	LastActivity      pgtype.Timestamp `json:"last_activity"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	TfaRememberMe     bool             `json:"tfa_remember_me"`
	TfaBypassUntil    pgtype.Timestamp `json:"tfa_bypass_until"`
	LastLoginIp       *string          `json:"last_login_ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.AccessTokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.DeviceFingerprint,
		arg.DeviceID,
		arg.LastActivity,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.TfaRememberMe,
		arg.TfaBypassUntil,
		arg.LastLoginIp,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM user_sessions WHERE expires_at < NOW() OR is_revoked = true
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteOldestTfaRememberSession = `-- name: DeleteOldestTfaRememberSession :exec
DELETE FROM user_sessions us
WHERE us.id = (
    SELECT s.id FROM user_sessions s
    WHERE s.user_id = $1 AND s.tfa_remember_me = true AND s.is_revoked = false AND s.expires_at > NOW()
    ORDER BY s.last_activity ASC
    LIMIT 1
)
`

func (q *Queries) DeleteOldestTfaRememberSession(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteOldestTfaRememberSession, userID)
	return err
}

const findSessionByUserAndDevice = `-- name: FindSessionByUserAndDevice :one
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions
WHERE user_id = $1 AND device_fingerprint = $2 AND is_revoked = false AND expires_at > NOW()
ORDER BY last_activity DESC
LIMIT 1
`

type FindSessionByUserAndDeviceParams struct {
	UserID            string  `json:"user_id"`
	DeviceFingerprint *string `json:"device_fingerprint"`
}

func (q *Queries) FindSessionByUserAndDevice(ctx context.Context, arg FindSessionByUserAndDeviceParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, findSessionByUserAndDevice, arg.UserID, arg.DeviceFingerprint)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.AccessTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.DeviceID,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.TfaRememberMe,
		&i.TfaBypassUntil,
		&i.LoginCount,
		&i.LastLoginIp,
	)
	return i, err
}

const findSessionByUserAndDeviceID = `-- name: FindSessionByUserAndDeviceID :one
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions
WHERE user_id = $1 AND device_id = $2 AND is_revoked = false AND expires_at > NOW()
ORDER BY last_activity DESC
LIMIT 1
`

type FindSessionByUserAndDeviceIDParams struct {
	UserID   string  `json:"user_id"`
	DeviceID *string `json:"device_id"`
}

func (q *Queries) FindSessionByUserAndDeviceID(ctx context.Context, arg FindSessionByUserAndDeviceIDParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, findSessionByUserAndDeviceID, arg.UserID, arg.DeviceID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.AccessTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.DeviceID,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.TfaRememberMe,
		&i.TfaBypassUntil,
		&i.LoginCount,
		&i.LastLoginIp,
	)
	return i, err
}

const findSessionWithTfaBypass = `-- name: FindSessionWithTfaBypass :one
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions
WHERE user_id = $1 AND device_fingerprint = $2 AND tfa_remember_me = true
  AND tfa_bypass_until > NOW() AND is_revoked = false AND expires_at > NOW()
ORDER BY last_activity DESC
LIMIT 1
`

type FindSessionWithTfaBypassParams struct {
	UserID            string  `json:"user_id"`
	DeviceFingerprint *string `json:"device_fingerprint"`
}

type FindSessionWithTfaBypassRow struct {
	ID                string           `json:"id"`
	UserID            string           `json:"user_id"`
	RefreshToken      string           `json:"refresh_token"`
	AccessTokenHash   *string          `json:"access_token_hash"`
	IpAddress         *string          `json:"ip_address"`
	UserAgent         *string          `json:"user_agent"`
	DeviceFingerprint *string          `json:"device_fingerprint"`
	LastActivity      pgtype.Timestamp `json:"last_activity"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	IsRevoked         bool             `json:"is_revoked"`
	TfaRememberMe     bool             `json:"tfa_remember_me"`
	TfaBypassUntil    pgtype.Timestamp `json:"tfa_bypass_until"`
	LoginCount        int32            `json:"login_count"`
	LastLoginIp       *string          `json:"last_login_ip"`
}

func (q *Queries) FindSessionWithTfaBypass(ctx context.Context, arg FindSessionWithTfaBypassParams) (FindSessionWithTfaBypassRow, error) {
	row := q.db.QueryRow(ctx, findSessionWithTfaBypass, arg.UserID, arg.DeviceFingerprint)
	var i FindSessionWithTfaBypassRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.AccessTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.TfaRememberMe,
		&i.TfaBypassUntil,
		&i.LoginCount,
		&i.LastLoginIp,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions WHERE id = $1 AND user_id = $2 AND is_revoked = false AND expires_at > NOW()
`

type GetSessionByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetSessionByID(ctx context.Context, arg GetSessionByIDParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, arg.ID, arg.UserID)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.AccessTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.DeviceID,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.TfaRememberMe,
		&i.TfaBypassUntil,
		&i.LoginCount,
		&i.LastLoginIp,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions WHERE refresh_token = $1 AND is_revoked = false AND expires_at > NOW()
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.AccessTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.DeviceFingerprint,
		&i.DeviceID,
		&i.LastActivity,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.IsRevoked,
		&i.TfaRememberMe,
		&i.TfaBypassUntil,
		&i.LoginCount,
		&i.LastLoginIp,
	)
	return i, err
}

const listSessionsByUserID = `-- name: ListSessionsByUserID :many
SELECT id, user_id, refresh_token, access_token_hash, ip_address, user_agent,
    device_fingerprint, device_id, last_activity, expires_at, created_at, is_revoked,
    tfa_remember_me, tfa_bypass_until, login_count, last_login_ip
FROM user_sessions WHERE user_id = $1 AND is_revoked = false AND expires_at > NOW() ORDER BY last_activity DESC
`

func (q *Queries) ListSessionsByUserID(ctx context.Context, userID string) ([]UserSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserSession
	for rows.Next() {
		var i UserSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshToken,
			&i.AccessTokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.DeviceFingerprint,
			&i.DeviceID,
			&i.LastActivity,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.IsRevoked,
			&i.TfaRememberMe,
			&i.TfaBypassUntil,
			&i.LoginCount,
			&i.LastLoginIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE user_sessions SET is_revoked = true WHERE user_id = $1
`

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, userID)
	return err
}

const revokeAllSessionsForUserExcept = `-- name: RevokeAllSessionsForUserExcept :exec
UPDATE user_sessions SET is_revoked = true WHERE user_id = $1 AND id != $2
`

type RevokeAllSessionsForUserExceptParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) RevokeAllSessionsForUserExcept(ctx context.Context, arg RevokeAllSessionsForUserExceptParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUserExcept, arg.UserID, arg.ID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE user_sessions SET is_revoked = true WHERE id = $1 AND user_id = $2
`

type RevokeSessionByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByID, arg.ID, arg.UserID)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE user_sessions SET last_activity = NOW() WHERE id = $1
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, id)
	return err
}

const updateSessionOnLogin = `-- name: UpdateSessionOnLogin :exec
UPDATE user_sessions SET
    refresh_token = $2,
    last_activity = $3,
    expires_at = $4,
    ip_address = $5,
    user_agent = $6,
    last_login_ip = $7,
    tfa_remember_me = $8,
    tfa_bypass_until = $9,
    device_id = COALESCE($10, device_id),
    login_count = login_count + 1
WHERE id = $1 AND user_id = $11
`

type UpdateSessionOnLoginParams struct {
	ID             string           `json:"id"`
	RefreshToken   string           `json:"refresh_token"`
	LastActivity   pgtype.Timestamp `json:"last_activity"`
	ExpiresAt      pgtype.Timestamp `json:"expires_at"`
	IpAddress      *string          `json:"ip_address"`
	UserAgent      *string          `json:"user_agent"`
	LastLoginIp    *string          `json:"last_login_ip"`
	TfaRememberMe  bool             `json:"tfa_remember_me"`
	TfaBypassUntil pgtype.Timestamp `json:"tfa_bypass_until"`
	DeviceID       *string          `json:"device_id"`
	UserID         string           `json:"user_id"`
}

func (q *Queries) UpdateSessionOnLogin(ctx context.Context, arg UpdateSessionOnLoginParams) error {
	_, err := q.db.Exec(ctx, updateSessionOnLogin,
		arg.ID,
		arg.RefreshToken,
		arg.LastActivity,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.LastLoginIp,
		arg.TfaRememberMe,
		arg.TfaBypassUntil,
		arg.DeviceID,
		arg.UserID,
	)
	return err
}
