// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trusted_devices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrustedDevice = `-- name: CreateTrustedDevice :exec
INSERT INTO user_trusted_devices (
    id, user_id, token_hash, device_id, user_agent, ip_address, label,
    created_at, last_used_at, expires_at, is_revoked
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, false)
`

type CreateTrustedDeviceParams struct {
	ID         string           `json:"id"`
	UserID     string           `json:"user_id"`
	TokenHash  string           `json:"token_hash"`
	DeviceID   *string          `json:"device_id"`
	UserAgent  *string          `json:"user_agent"`
	IpAddress  *string          `json:"ip_address"`
	Label      *string          `json:"label"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreateTrustedDevice(ctx context.Context, arg CreateTrustedDeviceParams) error {
	_, err := q.db.Exec(ctx, createTrustedDevice,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.DeviceID,
		arg.UserAgent,
		arg.IpAddress,
		arg.Label,
		arg.CreatedAt,
		arg.LastUsedAt,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredTrustedDevices = `-- name: DeleteExpiredTrustedDevices :exec
DELETE FROM user_trusted_devices
WHERE expires_at < NOW() OR is_revoked = true
`

func (q *Queries) DeleteExpiredTrustedDevices(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTrustedDevices)
	return err
}

const findValidTrustedDevice = `-- name: FindValidTrustedDevice :one
SELECT id, user_id, token_hash, device_id, user_agent, ip_address, label,
    created_at, last_used_at, expires_at, is_revoked
FROM user_trusted_devices
WHERE user_id = $1 AND token_hash = $2
  AND is_revoked = false AND expires_at > NOW()
LIMIT 1
`

type FindValidTrustedDeviceParams struct {
	UserID    string `json:"user_id"`
	TokenHash string `json:"token_hash"`
}

func (q *Queries) FindValidTrustedDevice(ctx context.Context, arg FindValidTrustedDeviceParams) (UserTrustedDevice, error) {
	row := q.db.QueryRow(ctx, findValidTrustedDevice, arg.UserID, arg.TokenHash)
	var i UserTrustedDevice
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.DeviceID,
		&i.UserAgent,
		&i.IpAddress,
		&i.Label,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.IsRevoked,
	)
	return i, err
}

const listTrustedDevicesForUser = `-- name: ListTrustedDevicesForUser :many
SELECT id, user_id, token_hash, device_id, user_agent, ip_address, label,
    created_at, last_used_at, expires_at, is_revoked
FROM user_trusted_devices
WHERE user_id = $1 AND is_revoked = false AND expires_at > NOW()
ORDER BY last_used_at DESC
`

func (q *Queries) ListTrustedDevicesForUser(ctx context.Context, userID string) ([]UserTrustedDevice, error) {
	rows, err := q.db.Query(ctx, listTrustedDevicesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserTrustedDevice
	for rows.Next() {
		var i UserTrustedDevice
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenHash,
			&i.DeviceID,
			&i.UserAgent,
			&i.IpAddress,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.IsRevoked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllTrustedDevicesForUser = `-- name: RevokeAllTrustedDevicesForUser :exec
UPDATE user_trusted_devices
SET is_revoked = true
WHERE user_id = $1 AND is_revoked = false
`

func (q *Queries) RevokeAllTrustedDevicesForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllTrustedDevicesForUser, userID)
	return err
}

const revokeTrustedDeviceByID = `-- name: RevokeTrustedDeviceByID :exec
UPDATE user_trusted_devices
SET is_revoked = true
WHERE id = $1 AND user_id = $2
`

type RevokeTrustedDeviceByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) RevokeTrustedDeviceByID(ctx context.Context, arg RevokeTrustedDeviceByIDParams) error {
	_, err := q.db.Exec(ctx, revokeTrustedDeviceByID, arg.ID, arg.UserID)
	return err
}

const touchTrustedDeviceLastUsed = `-- name: TouchTrustedDeviceLastUsed :exec
UPDATE user_trusted_devices
SET last_used_at = $2
WHERE id = $1
`

type TouchTrustedDeviceLastUsedParams struct {
	ID         string           `json:"id"`
	LastUsedAt pgtype.Timestamp `json:"last_used_at"`
}

func (q *Queries) TouchTrustedDeviceLastUsed(ctx context.Context, arg TouchTrustedDeviceLastUsedParams) error {
	_, err := q.db.Exec(ctx, touchTrustedDeviceLastUsed, arg.ID, arg.LastUsedAt)
	return err
}
