fullnameOverride: patchmon

config:
  corsOrigin: "http://localhost:3000,http://127.0.0.1:3000"

secret:
  create: false
  existingSecretName: patchmon-app-secrets

database:
  enabled: true
  persistence:
    enabled: false

redis:
  enabled: true
  persistence:
    enabled: false

ingress:
  enabled: false
