{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.redisServiceName" . }}
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
  {{- with .Values.redis.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
  selector:
    {{- include "patchmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
