apiVersion: v1
kind: Service
metadata:
  name: {{ include "patchmon.fullname" . }}-server
  labels:
    {{- include "patchmon.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
  {{- with .Values.server.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "patchmon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
